### ISSUE TITLE
Feature idea: synced metronom

### ISSUE THREAD

**Issue by github-luckow-org** [corrados/jamulus#114]
Hi,

I love & use your software for my choir. Initial setup is nothing for noobs. But after a few rehearsals it's okayish. 

One missing peace: a synced metronom. Today one of us needs to play an analog metronom through the mic. I'm not a developer but imho it's not rocket science to sync a jamulus client metronom against the server instance :)
The idea is to choose between a click or an optical sign.

**Comment by corrados** [comment]
Duplicate, see here: https://github.com/corrados/jamulus/issues/79

**Comment by drummer1154** [comment]
Hello Volker,
I do not understand what is going on here.
In [https://github.com/corrados/jamulus/issues/79](url) you say "I do not like the idea of having a metronome in Jamulus.", closed the issue and refer to this one which you in turn close and declare it as duplicate to #72 so the cat bites its tail!
Even if I can understand that you do not want to put effort on the metronome issue, this is not the expected way feature requests are treated. Some background info:
- I am the drummer of a three peace jazz/rock/fusion group and we are desperately searching for a way to practice over the Internet. Currently the only working platform appears to be JamKazam as we need 44.1 kHz sample rate support (which to my Jamulus research and trial/error effort on the last three days Jamulus does not have but I did not find any related info on the prominent help pages). Main reason is my V-Drums TD-20 which runs on 44.1 kHz on the S/PDif interface and I want to avoid unnecessary D/A - A/D conversions.
My experience with the JamKazam metronome (from one session) is that we tried to follow each other as well as to the metronome but we run out of synch when due to network interruptions the JamKazam metronome was behind (or before - this I cannot remember).
Conclusion: I agree that it is a very good idea to have a central audible synching clock - but implementation appears to be not "keep it simple and stupid" ...

**Comment by corrados** [comment]
Hmm, #79 is still open. No cat bites in its tail. But maybe I misunderstood your post. If you really want to have two Issues about the same topic, I can reopen the Issue again.

**Comment by corrados** [comment]
BTW, I also run a TD-20 over S/PDif in my Lexicon Omega and it works great with 48 kHz.

**Comment by drummer1154** [comment]
No. I do not want to have 2 issues for the same thing in parallel. I only do not see a clear conclusion which issue is maintained and which one is closed.
BTW, my TD-20 is connected to a Focusrite Scarlett 18/20 and I need to set the Scarlett to 44.1 kHz or else no sound is transferred to USB - which is the case if I select it as input for Jamulus...
I think this goes beyond public discussion - if you are in the Apple community you may send an iMessage to +491604391246 - I am (as a retired SW developer and project manager) new to Git and Sourceforge and registered on both only lately - how to exchange PMs ...
Cheers
Helmuth

**Comment by drummer1154** [comment]
A remark to Volker's input
> BTW, I also run a TD-20 over S/PDif in my Lexicon Omega and it works great with 48 kHz.

I think in the Owner's Manual, Omega Signal Routing Diagram, I have found the reason why it is working: The Omega has a sample rate converter at the S/PDIF input, the Scarlett obviously not...
