### ISSUE TITLE
Connect software to jamulus via JACK with different buffer size and sampling frequency

### ISSUE THREAD

**Issue by vocobox** [corrados/jamulus#142]
I am trying to **send sound generated by a software synthetizer to a Jamulus session**. As pointed by @trebmuh in https://github.com/corrados/jamulus/issues/82, JACK is a good choice for that. However, it seams that JACK is not able to deal with a sound consumer and producer with different buffer size or sampling frequency. Did anyone achieved to send software sound to Jamulus via JACK?

Here's [my post on JACK issue list](https://github.com/jackaudio/jack2/issues/566). I unfortunately get no answer.

I am trying to use Jack 2 (0.92_B3) on MacOS 10.12.6 to send audio from an Arturia drum machine (the producer) to Jamulus (the consumer). I ran JackPilot and wonder if it can be used to share audio content between applications with different audio settings.

Connecting the sound producer to Jack

* Each time I try to select Jack in Spark device list, Spark display an error message : "Couldn't change buffer size". I tried all buffer size setting in Jack without success. **How can I guess the expected buffer size on the producer application? Is it possible to let Jack adapt to it?** Spark does not display sampling frequency and buffer size until the device is loaded.

Connecting the sound consumer to Jack
* At the beginning Jamulus threw an error asking for 48KHz sampling frequency. This halted the Jack server with an error popup, so I restarted the Jack server with 48KHz setting.
* When trying to select Jack as input in Jamulus, JackPilot pops another error : "Another application has changed the sampling rate" which is surprising, since the two applications where both on the same sampling rate.
* Then restart Jamulus and Jack with 48KHz, it is fine.
**Will Jack be able to resample from consumer to producer sampling rates automatically?**

NB : Hog mode is off.

**Comment by jkbd** [comment]
If you start a JACK-Server, you set sample-rate, buffer size of the cycle and the number of buffers. Audio-applications should adapt to these settings. Theoretically applications should be capable of running with dynamically changing cycle size, so only sample-rate should be a concern.

From my understanding so far, Jamulus uses 48kHz sample-rate, because the OPUS codec does not support 44.1kHz. JACK is not meant to resample frame-rates between applications. Resampling would have to be implemented in Jamulus.

I don't know about macOS and JackPilot quirks. Please try to make sure, that no program tries to reconfigure or override JACK settings.

**Comment by corrados** [comment]
What do we do with this issue here? Jamulus needs 48 kHz but it should be possible to use any buffer size.

I think this is about Jack audio and not Jamulus. Maybe we should close this issue?

**Comment by vocobox** [comment]
Yes, thanks for asking.
