### ISSUE TITLE
Honour own fader and Mute button in “Mute Myself”

### ISSUE THREAD

**Issue by softins** [corrados/jamulus#148]
“Mute Myself” is a great feature, but when selected, I hear myself at full volume. My fader doesn’t control the volume, and the Mute button on my channel is also ignored.

It would be great if the local mix of my channel in that mode could take account of my own fader and Mute button.

**Comment by elliotclee** [comment]
What I found was that when I connected to a server, I could hear myself even with "Mute Myself" on, "Mute" on my channel, and the slider all the way down.

When I disconnect from a server I didn't hear myself at all, so it is something to do with Jamulus or some weird feature of my sound setup.

This is on Windows with ASIO4ALL. I don't know if there is something about my setup that is doing software monitoring.

While doing this, I also discovered that the "Mute" and "Solo" buttons can be set at the same time. Should be mutually exclusive...

**Comment by pljones** [comment]
Audio only gets to Jamulus audio outs when it's receiving audio from a server.

"Mute myself" means "Bypass the server".  It stops anyone else on the server hearing you, muting you.

The input fader then lets you adjust your level.

Ideally you should never need to use the mixer fader for your own level, only the input fader.

**Comment by softins** [comment]
What input fader? Jamulus doesn’t have one, does it?

The point is, if for reasons of balance I have my own fader at a lower level than 100%, then if I click on Mute Myself, what I hear of myself suddenly changes to full volume. It should stay the same. My signal should be multiplied by the fader position on my channel when mixing directly to my output. And while doing that it would be sensible and complete to obey the Mute button on my channel too.

Once more familiar with the code, I could submit a PR for it, but I’m sure Volker would know immediately how to do it.

**Comment by corrados** [comment]
It is not trivial. The client does not know which fader is his. You could compare the fader name with yours but if another has given his fader the same name, you have ambiguous results.

Why do you not have your fader on maximum? I am right now working on improving the sound card audio input stream selection. In the future you will be able to change the input gain of each input stream of your sound card. Then you can do the attenuation there instead of the server mixer.

**Comment by softins** [comment]
> It is not trivial. The client does not know which fader is his. You could compare the fader name with yours but if another has given his fader the same name, you have ambiguous results.

OK, I understand.

> Why do you not have your fader on maximum?

Often I do, but if in a group where some of the participants have a lower signal level, I might set myself lower so I can hear them better. After all, the faders must be there for a purpose, not just to leave on maximum!

**Comment by pljones** [comment]
> What input fader? Jamulus doesn’t have one, does it?
Sorry, it will do, with Volker's coming changes.

**Comment by sthenos** [comment]
I never have fader's on maxium, I leave them all including mine around 70% level which gives me wiggle room to adjust and balance other people up or down as the mix necessitates.  I would agree mute myself should not force my own signal to be amplified to the maxium but respect the level of my own fader.

**Comment by corrados** [comment]
> Why do you not have your fader on maximum?

Maybe my question was a bit misleading. I do not want to say that this issue should not be fixed. I agree with you, that this is a bug and should be fixed. But I also said that it is not trivial to do it in a clean way.

**Comment by Matzix** [comment]
I just had left a comment in [issue #187 ](https://github.com/corrados/jamulus/issues/187#issuecomment-628243612) . It might be helpful to have a local direct monitoring feature (with its own fader), which can be enabled only, if "mute myself" is selected. That way, your own fader in the server mixing section is irrelevant then, as your signal will not be sent to the server anyway.

**Comment by Matzix** [comment]
As announced in issue #187, here is my idea, on how the "mute myself" behavior might be improved.

Let's start with a signal flow diagram for the current implementation - at least, how I think it might be from a functional point of view:

![grafik](https://user-images.githubusercontent.com/15308822/82125249-eaec3200-97a4-11ea-9dc8-e9f403b7cb38.png)

The main idea is to have a separate fader, mute and solo button for the direct monitoring path.
- As it is now, these controls should have an effect only, if no data are sent to the server. Otherwise direct monitoring should always be off.
- As the direct monitoring signal might be disabled (mute on, solo off), it would be great to have this path also active when not connected to a server (e.g. for soundcheck)
- If solo is pressed for direct monitoring, also the personal server mix should switch to solo mode (i.e. everything be muted, if no solo button has been selected there). The other way round, if solo is selected for a server channel, but not for direct monitoring, the direct signal might be muted.

This is, how the signal flow diagram might look like (Simulink ain't no graphic tool...):

![grafik](https://user-images.githubusercontent.com/15308822/82125709-1ae90480-97a8-11ea-98e3-020a5c1dee29.png)

That way, you would be able to do
- soundcheck, when not connected yet or with mute myself and direct monitoring solo on when connected
- tune your instrument with reference from other musician: select solo for the corresponding server channel, mute myself on, direct monitoring solo on.
- mute your signal completely (i.e. on server and locally), e.g. when you are fixing problems with your equipment (e.g. exchanging cables) and still want to listen to others.

For the GUI, i've used photoshop for how it might look like:

![grafik](https://user-images.githubusercontent.com/15308822/82125946-9e572580-97a9-11ea-9aa0-90c17b6db9ad.png)

For the direct monitoring controls, they might be hidden or disabled in normal operation (i.e. mute myself off) or set to a fixed state (mute on, solo off), such that it it obvious, that this path can be used only when not streaming your own signal to the server. Another GUI enhancement might be to indicate, whether a user has selected "mute myself" by turning the first signal LED to red. This would also be an improvement regarding issue #187, as the signal LED for your own channel would turn red in the server section, if "mute myself" has been selected.

**Comment by WolfganP** [comment]
Thx a lot @Matzix for the diagram, I'm relatively new to Jamulus and I struggled to understand what each UI control really does in the signal flow even if I have experience with mixer boards and read the wiki and many forum discussions.

Maybe a good addition to the wiki will be adding your diagram (augmented with the missing controls for Pan and Reverb) side by side the Jamulus main UI with arrows indicating each switch where it relates too, so anyone experienced in a band can support other no so techy members using the central documentation.

**Comment by corrados** [comment]
> mute your signal completely (i.e. on server and locally), e.g. when you are fixing problems with your equipment (e.g. exchanging cables) and still want to listen to others.

This is the only mode which is not supported in Jamulus. But I find this mode not very useful. You could quickly disconnect from the server, exchanging cables and re-connect. Why do you have to listen for the others while exchanging cables since you are busy with changing cables anyway ;-).

**Comment by Matzix** [comment]
> > mute your signal completely

> (...) I find this mode not very useful. (...) Why do you have to listen for the others

Exchanging cables was just an example. With our orchestra, we currently try to set up rehearsals with Jamulus. It might be 30 people joining on a private server. It's not just playing all the time, but our conductor will also talk to us or some conversation be done. We don't have pickups for our instruments (mostly violins), but use microphones. Last week on a rehearsal test, my 8-year old nephew came in and started to make lots of noise. _This_ is really a situation, where you neither want to distribute nor listen to your own signal, but still listen to your conductor.

> This is the only mode which is not supported in Jamulus.

Direct monitoring without being connected to a server isn't, either. And of course, solo for direct monitoring can be achieved by muting all server signals one-by-one, but with lots of people on a server, this is quite troublesome.

Not every person will make use of the different modes, which the extra mute and solo buttons will provide, but I am quite confident, that a lot of users will benefit from it, too. Furthermore, it might improve, that Jamulus behaves as expected: I was quite surpised, that "mute myself" doesn't stop my own signal to be heard. If there is an additional direct monitoring entry with its own mute button, which does the trick, it's easy to understand, what's going on.

**Comment by corrados** [comment]
> This is really a situation, where you neither want to distribute nor listen to your own signal, but still listen to your conductor.

I would say this is still a special case. I would recommend a hardware solution by, e.g., turn down the input volume knob in that case.

> Direct monitoring without being connected to a server isn't, either.

For what reason do you need this?

> And of course, solo for direct monitoring can be achieved by muting all server signals one-by-one, but with lots of people on a server, this is quite troublesome.

It's much simpler, just press Mute Myself and set your own fader to Solo.

> the extra mute and solo buttons will provide, but I am quite confident, that a lot of users will benefit from it, too.

My opinion is different. We had endless discussions about "Mute Myself", not only in this thread. Now you want to introduce another Mute and Solo. This will even increase the confusion.

> I was quite surpised, that "mute myself" doesn't stop my own signal to be heard.

The confusion is just about the name. The functionality is very useful.

> If there is an additional direct monitoring entry with its own mute button, which does the trick, it's easy to understand, what's going on.

See above: Introducing even more settings will not solve the issue. Also, I want to keep the number of controls in the main window to a minimum.

**Comment by Matzix** [comment]
> I would recommend a hardware solution

This is a argument, which also could be used against your statements: You could use the direct monitoring function of your soundcard and mute the signal path to Jamulus, such that you don't need "mute myself" either :-) 

It's handy to have required and often-used controls in one place (i.e. in the Jamulus GUI) and not every user owns the appropriate hardware to achieve this or wants to spend money just because of that. And even some expensive soundcards do not have hardware buttons at all.

> The confusion is just about the name. The functionality is very useful.

... for those, who like it :-). It's a _matter of taste_. Some like it that way it is, others already have stated, that they would prefer to have the direct monitoring path removed. With my suggested extension, it still might behave like it is, but you might have it also the other way, as the two functionalities are somehow separated from each other. I disagree, that the confusion is just about the name, but I've written about that already and won't repeat myself here.

> For what reason do you need this?

Direct Monitoring without a connection to a server might be used to setup your hardware and your input sound (including pan and reverb of Jamulus) completely before connecting to a server - especially as a server connection is not required for this task.

> Now you want to introduce another Mute and Solo. This will even increase the confusion.

Essentially, these button behave the same way, as those for each musician's channel in the server section do. If users are familiar to these buttons, they still will be. And there won't be a mix of two functionalities in one button any more. In my personal opinion, it would be a lean approach with additional benefits in terms of clearness and flexibility. If this all will increase or decrease confusion requires user feedback and that's one of the reasons, why I've added a figure, how it could look like. I admit, that it might be challenging to have a look-and-feel, which makes it easy to comprehend, that direct monitoring is enabled only in case of "mute myself" being active, but hey: currently it isn't, either... 

> We had endless discussions about "Mute Myself", not only in this thread. 

I don't like endless discussion, either - especially, when they are not productive. So, I'd further like to emphasize on pro/contra arguments and on usage scenarios for different users. If it is about implementing these things, I'd happy being able to contribute, but I'm lacking both C++ knowlegde and experience (just having had a lecture in university several years ago won't do...)

> Also, I want to keep the number of controls in the main window to a minimum.

I agree to 100%. Thank you very much for your efforts!

**Comment by WolfganP** [comment]
> Let's start with a signal flow diagram for the current implementation - at least, how I think it might be from a functional point of view:
> 
> ![grafik](https://user-images.githubusercontent.com/15308822/82125249-eaec3200-97a4-11ea-9dc8-e9f403b7cb38.png)

[OFF TOPIC] @Matzix I'm playing around the idea of augmenting the documentation and your diagrams feels like a good place to start. Do you mind to post the sources for easier editing/augmentation?

**Comment by corrados** [comment]
Should be fixed by now. But please note: For the fixed functionality to work correctly, the server version must be >= **3.5.5**! This is because I had to introduce a new protocol message which comes from the server and tells the client the fader ID.
