### ISSUE TITLE
Move Central Server Address Dropdown to Connection Setup

### ISSUE THREAD

**Issue by Snayler** [corrados/jamulus#157]
I currently find myself having both the Settings and Connection Setup windows opened in order to check for users on other servers, by changing the Central Server on Settings and switching to Connection Setup to view the results.

My suggestion is to move the Central Address Dropdown (or maybe duplicate it) so that people can just use the Connection Setup window for that effect, changing the Central Server and getting the results on the same window.

**Comment by corrados** [comment]
The idea of the different server lists are that you only get servers shown which are located near new. It does not make sense if you are in Europe to connect to a server located in the US.

**Comment by Snayler** [comment]
It does happen a lot that when the Default server is full, people near me start creating servers on the North America Central Server, hence the need to switch between both Central Servers to find those servers.

Also, for listeners, to whom the latency is not an issue, having the ability to switch servers on the same window to find jam sessions is a plus.

**Comment by sthenos** [comment]
If i could add.  Quite a few of us are creating "central servers" for other more private uses.  For instance for the world jam events we have a central server which has 5 other server rooms connected to it which is used just for the world jam and the streaming that goes out to facebook/youtube.    I would definately favour and vote for this option.

**Comment by corrados** [comment]
@sthenos I, too, like this idea. So we have to come to a point where we have multiple "Central Servers". The problem is that these servers must be on 24/7 and they must be reliable. Imagine someone manages a separate server list (e.g. a "Jazz" or "Rock" server list) and there are 100 other servers listed but suddenly the server list operator doesn't like Jamulus anymore and shuts down his server list. Then all these other 100 servers are no longer listed at any server list.
The problem is: When we have other central server, how do we get the information about these lists in the Jamulus server GUI. Right now there is a hard-coded URL implemented in the server so it always finds my Central server. If multiple lists are available, some dynamic query of server URLs or IPs have to be supported. This is not a trivial task. And we have some server operators which start the Jamulus server on the command line under Linux. They do not even have a GUI.

**Comment by Snayler** [comment]
@corrados 

>The problem is: When we have other central server, how do we get the information about these lists in the Jamulus server GUI

For the sake of enabling Central Server expansion, how about having a new server hierarchy where a higher server would announce the current Central Servers? This would effectively allow to have multiple Central Servers listed (some from you, others from other users) and the client would just consult the current Central Server list to show the users. Any newly created central server would be announced to the main server (unless specified in the settings, thinking about private central servers) and you could divide them by category (Official servers / Custom servers). The main server would check if a central server went down and remove it from the list. 

>Then all these other 100 servers are no longer listed at any server list.

Well, that's the cost of running a server. Any active server owners would detect this and move their server to another Central server.

**Comment by corrados** [comment]
I just implemented it -> closed.
