### ISSUE TITLE
--showallservers "ping" column sort is alphabetic

### ISSUE THREAD

**Issue by pljones** [corrados/jamulus#201]
The "ping" time should be sorted numerically.  Currently it's 1, 10, 100, 2, 20, 200, 3, 30, 300, 4... etc.

**Comment by corrados** [comment]
For the normal list I do the sorting correctly by appending zeros at the beginning. Since this ping time is shown and we want to sort by the visible number, I think it would look ugly to prepend zeros. Since the --showallservers is an undocumented feature and only for debugging, I would consider this issue as a minor, maybe even never fix this.

**Comment by pljones** [comment]
Yeah, definitely minor.  I was needing it for some testing the other night, so I'll maybe pick it up.

**Comment by corrados** [comment]
This should be fixed now -> closed
