### ISSUE TITLE
Stereo Channel Splitting

### ISSUE THREAD

**Issue by seanogdelaney** [corrados/jamulus#211]
Again, congratulations and thanks to the Jamulus authors.

A feature suggestion, if I may:

Many players both sing and play simultaneously (e.g. mic + guitar input). It would be useful to have a switch for such cases, to create two mono channels in the mixer, with separate volume controls.

Currently, the relative volume of the mic and guitar is fixed for all players by the originating player. This is not ideal, for example if another player wants to hear the guitar clearly, but sing a harmony.

**Comment by corrados** [comment]
Your request is a special case of this: https://github.com/corrados/jamulus/issues/96
As a workaround you could start two instances of Jamulus. It is not officially supported but a lot of users have successfully used this method.
Since this Issue is so similar to the other, I would like to close this one and keep the other one open. Is this ok for you?

**Comment by seanogdelaney** [comment]
Yes, my apologies, this is the same feature, thank you!

Possibly off topic, could a trim value be added to each channel? Many physical mixers have one, for constant gain or attenuation prior to the mixer slider. The sliders allow attenuation, so there is no way to boost weak signals.

**Comment by corrados** [comment]
> Possibly off topic, could a trim value be added to each channel?

We already had a discussion going on about this topic, see: https://github.com/corrados/jamulus/issues/97

**Comment by seanogdelaney** [comment]
Thanks!
