### ISSUE TITLE
Latest release not compiling under Ubuntu 18.04

### ISSUE THREAD

**Issue by sthenos** [corrados/jamulus#217]
Following the headless ubuntu server instructions latest release is not compiling on AWS EC2 Ubuntu 18.04 LTS.     Should we be doing something different?

`git clone https://github.com/corrados/jamulus.git llcon-jamulus`

Dependencies installed are:

```
sudo apt update
sudo apt install build-essential libqt4-dev
```

qmake also gives an error now and never used to:

```
ubuntu@ip-172-31-27-3:~/llcon-jamulus$ qmake "CONFIG+=nosound" Jamulus.pro
src/resources.qrc: Warning: potential duplicate alias detected: 'translation.qm'
src/resources.qrc: Warning: potential duplicate alias detected: 'translation.qm'
src/resources.qrc: Warning: potential duplicate alias detected: 'translation.qm'
```

make then gives following errors:

```
src/signalhandler.cpp:144:122: error: no matching function for call to ‘QObject::connect(QSocketNotifier*&, void (QSocketNotifier::*)(int), CSignalHandler*&, void (CSignalHandler::*)(int))’
         QObject::connect ( socketNotifier, &QSocketNotifier::activated, nPSignalHandler, &CSignalHandler::OnSocketNotify );
                                                                                                                          ^
In file included from /usr/include/qt4/QtCore/QObject:1:0,
                 from src/signalhandler.h:64,
                 from src/signalhandler.cpp:62:
/usr/include/qt4/QtCore/qobject.h:204:17: note: candidate: static bool QObject::connect(const QObject*, const char*, const QObject*, const char*, Qt::ConnectionType)
     static bool connect(const QObject *sender, const char *signal,
                 ^~~~~~~
/usr/include/qt4/QtCore/qobject.h:204:17: note:   no known conversion for argument 2 from ‘void (QSocketNotifier::*)(int)’ to ‘const char*’
/usr/include/qt4/QtCore/qobject.h:217:17: note: candidate: static bool QObject::connect(const QObject*, const QMetaMethod&, const QObject*, const QMetaMethod&, Qt::ConnectionType)
     static bool connect(const QObject *sender, const QMetaMethod &signal,
                 ^~~~~~~
/usr/include/qt4/QtCore/qobject.h:217:17: note:   no known conversion for argument 2 from ‘void (QSocketNotifier::*)(int)’ to ‘const QMetaMethod&’
/usr/include/qt4/QtCore/qobject.h:337:13: note: candidate: bool QObject::connect(const QObject*, const char*, const char*, Qt::ConnectionType) const
 inline bool QObject::connect(const QObject *asender, const char *asignal,
             ^~~~~~~
/usr/include/qt4/QtCore/qobject.h:337:13: note:   no known conversion for argument 2 from ‘void (QSocketNotifier::*)(int)’ to ‘const char*’
Makefile:1750: recipe for target 'signalhandler.o' failed
make: *** [signalhandler.o] Error 1

```

**Comment by pljones** [comment]
Duplicate.

See https://github.com/corrados/jamulus/issues/214#issuecomment-628744732 and https://github.com/corrados/jamulus/issues/168#issuecomment-627988221

**Comment by corrados** [comment]
> sudo apt install build-essential libqt4-dev

This is the issue. I think we need to drop Qt4 support now.

**Comment by sthenos** [comment]
Ah ok. what should I do instead?

**Comment by corrados** [comment]
This should be up-to-date: https://github.com/corrados/jamulus/wiki/Installation-for-Linux

**Comment by jerogee** [comment]
@corrados , I deployed Jamulus now a few times now on Ubuntu. What about making a deployment script that does everything from system checks to up deliver an up and running server? That would make it easier to get a server up. I am happy to develop it and keep it up to date. What is in distributions/ can be taken a starting point.

**Comment by corrados** [comment]
Jamulus version 3.5.2 will be the last version which is compatible with Qt4. All newer versions will required at least Qt5.

@sthenos I assume that you solved your compilation error by installing the qt5 packets so I will close this issue. If you still have problems with the build, just re-open this issue again.

**Comment by corrados** [comment]
@jerogee I guess the cleanest solution would be that Jamulus will be included in Linux distributions. But I don't know if this will happens sometime soon or at all...

**Comment by dubnemo** [comment]
@corrados 
I have similar issues compiling the latest.
I first retrieved qt5:
sudo apt-get install build-essential qtdeclarative5-dev qttools5-dev-tools 

but make gave me
g++ -c -pipe -O2 -D_REENTRANT -Wall -W -DAPP_VERSION=\"3.5.5git\" -DOPUS_BUILD -DUSE_ALLOCA -DCUSTOM_MODES -D_REENTRANT -DHAVE_LRINTF -DHAVE_STDINT_H -DWITH_SOUND -DQT_NO_DEBUG -DQT_XML_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtXml -I/usr/include/qt4 -Isrc -Ilibs/opus/include -Ilibs/opus/celt -Ilibs/opus/silk -Ilibs/opus/silk/float -Ilibs/opus/silk/fixed -I. -I. -o audiomixerboard.o src/audiomixerboard.cpp
src/audiomixerboard.cpp: In member function 'void CChannelFader::Reset()':
src/audiomixerboard.cpp:314:16: error: 'class QLabel' has no member named 'setToolTipDuration'; did you mean 'setToolTip'?
     plblLabel->setToolTipDuration       ( iToolTipDurMs );

Then I tried to start all over by removing everything, since I see qt4 references:
sudo apt-get remove build-essential qtdeclarative5-dev qttools5-dev-tools libjack-jackd2-dev
sudo apt-get remove build-essential libqt4-dev libjack-jackd2-dev
And removing all jamulus folders (old versions included).

Starting over per the Linux install page, qmake seems to have a problem building target.

pi@raspberrypi:~/jamulus $ qmake Jamulus.pro
Project MESSAGE: Jack Audio Interface Enabled.
**/home/pi/jamulus/Jamulus.pro:298: Unknown replace function: absolute_path**
src/resources.qrc: Warning: potential duplicate alias detected: 'translation.qm'
src/resources.qrc: Warning: potential duplicate alias detected: 'translation.qm'
src/resources.qrc: Warning: potential duplicate alias detected: 'translation.qm'
src/resources.qrc: Warning: potential duplicate alias detected: 'translation.qm'
src/resources.qrc: Warning: potential duplicate alias detected: 'translation.qm'
WARNING: target.path is not defined: **install target not created**

so subsequently make has problems (I still see qt4 references):
pi@raspberrypi:~/jamulus $ make
/usr/lib/arm-linux-gnueabihf/qt4/bin/uic src/clientdlgbase.ui -o ui_clientdlgbase.h
/usr/lib/arm-linux-gnueabihf/qt4/bin/uic src/serverdlgbase.ui -o ui_serverdlgbase.h
/usr/lib/arm-linux-gnueabihf/qt4/bin/uic src/clientsettingsdlgbase.ui -o ui_clientsettingsdlgbase.h
/usr/lib/arm-linux-gnueabihf/qt4/bin/uic src/chatdlgbase.ui -o ui_chatdlgbase.h
/usr/lib/arm-linux-gnueabihf/qt4/bin/uic src/connectdlgbase.ui -o ui_connectdlgbase.h
/usr/lib/arm-linux-gnueabihf/qt4/bin/uic src/aboutdlgbase.ui -o ui_aboutdlgbase.h
g++ -c -pipe -O2 -D_REENTRANT -Wall -W -DAPP_VERSION**=\"3.5.5git\**" -DOPUS_BUILD -DUSE_ALLOCA -DCUSTOM_MODES -D_REENTRANT -DHAVE_LRINTF -DHAVE_STDINT_H -DWITH_SOUND -DQT_NO_DEBUG -DQT_XML_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I/usr/share/**qt4**/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtXml -I/usr/include/qt4 -Isrc -Ilibs/opus/include -Ilibs/opus/celt -Ilibs/opus/silk -Ilibs/opus/silk/float -Ilibs/opus/silk/fixed -I. -I. -o sound.o linux/sound.cpp
In file included from linux/sound.cpp:27:
linux/sound.h:35:10: fatal error: QThread: No such file or directory
 #include <QThread>
          ^~~~~~~~~
compilation terminated.
make: *** [Makefile:1491: sound.o] Error 1

**Comment by corrados** [comment]
Have you tried to install the `qt5-default` package?

**Comment by dubnemo** [comment]
@corrados 
**yes, that worked.**  
So the install page:
https://github.com/corrados/jamulus/wiki/Installation-for-Linux
Under 
"On Debian 11 (bullseye) or later, and **Raspberry Pi Raspbian Buster** release or later, use"
needs updating, similar to Ubuntu :
sudo apt-get install build-essential qtdeclarative5-dev qttools5-dev-tools qt5-default libjack-jackd2-dev
Thanks.

**Comment by corrados** [comment]
Great. Can you please apply the changes in the Wiki?

**Comment by Snayler** [comment]
I've updated the wiki with this information
