### ISSUE TITLE
Why does raspijamulus.sh use Opus 1.1?

### ISSUE THREAD

**Issue by streaps** [corrados/jamulus#252]
I wonder why raspijamulus.sh uses Opus version 1.1 instead of 1.3.1?

https://github.com/corrados/jamulus/blob/49b43c04bb6d07ed15643b31483c1c524a4e0535/distributions/raspijamulus.sh#L4

**Comment by corrados** [comment]
Because this file was not updated yet.

**Comment by corrados** [comment]
Since we now should use ARM for the integrated Opus version, it may not be required to use Opus in a separated library at all for the Pi Zero. So this code may be removed completely from the script.

**Comment by corrados** [comment]
I just tried out the following:

- Do not use OPUS in shared library but use the version which is included in the jamulus source code: instead of 80 % load I get 90 % load on my Raspberry Pi Zero
- Do not use OPUS in shared libaray but use the version which is included in the Jamulus source code but try to compile in fixed-point: I get compilation errors so this is not possible right now
- I replaced the opus-1.1 with OPUS="opus-1.3.1" in the raspijamulus.sh -> OPUS version 1.3.1 has a known but with the custom interface. If I use that version as a shared libaray, I get a runtime error on starting Jamulus. So this is also not possible. We have to wait for the next official OPUS version.

Therefore it is the best to keep the opus-1.1 version as is in the raspijamulus.sh file. I close this issue now.
