### ISSUE TITLE
Improve server log with disconnect message and time

### ISSUE THREAD

**Issue by Snayler** [corrados/jamulus#277]
It would be nice the improve the server log with a message of which client disconnected and when this happened. As it is right now it only shows connected clients, but doesn't show when they disconnected.

**Comment by corrados** [comment]
Referring to the following pull request: https://github.com/corrados/jamulus/pull/407

Why do you need to log the disconnection of a user? This increases the size of the log file significantly but gives just little information value. In the current log you can see the IP addresses of all connected users. And if all users have disconnect, the server stops and this is also logged.

What benefit do you have by having the information about the disconnects?

**Comment by storeilly** [comment]
Hi sir.
I am aware that it does double the size of the log file, but provides a better indication of how much a server is used. It is helpful to me to compare the number of connected users with the graphs provided by the server operators, to select the most optimum servers for our use.

**Comment by corrados** [comment]
I am not convinced. If the server is frequently used, you will not get much information from the graph anyway since the markers overlap a lot.
What are the criteria for your selction of the optimum server to use? If the criteria is simply how many people join the server over a period of, let's say, one day, then it is enough to see when they have connected the server. And, of course, see when the server goes back to idle.

**Comment by storeilly** [comment]
Criteria is, what server will hold enough singers before hitting 100% usage. I know this will change when multi threading options are available but for now I need to know how much I need to spend to have a workable system. I've been promoting Jamulus for choral singing worldwide and need to know how to accommodate large groups.

**Comment by corrados** [comment]
Oh, I see. Are you the Stephen from the Facebook Choral Community group?

> [...] to compare the number of connected users with the graphs provided by the server operators

Ok, so your intention is to see how many clients are connected at the same time. Makes sense. But still the question is how you correlate the entries in the Jamulus log with your CPU usage graph. If, according to the Jamulus log, 30 people are connected to a server, you do not know if the server was stable or not at that time. Or do you have more enhanced monitoring tool available for that?

**Comment by storeilly** [comment]
Yes that's me.
No advanced tools yet, this was supposed to be a starting point. Knowing
how many users are connected and when. There is no point trying to
understand why users complain about sound quality without knowing how many
users were connected at that time. I have user reports at least, but users
only report what they notice. In order to diagnose anything there needs to
be records to compare to. I also had a group complain they were being
kicked off the server, it turns out it was only one user. Yes, user problem.

**Comment by WolfganP** [comment]
My take is that the log file is useful to troubleshoot issues (ie certain user rate of dis/re/connections, IP ranges, etc) due it's events timestamping nature. 

For stats & correlation purposes, isn't it better to capture useful info via regular cron-ed scripts like --htmlstatus file with some OS info at the same time? (ie `htmstatus` + `top -b -n 1`)

**Comment by corrados** [comment]
Good to know. It's a little off-topic but: Thank you for building and maintaining a community of online singers. It's great to see all the people using Jamulus.

I would like to support you with your issues. But I fear that the solution with the Jamulus log file will not solve it. If it is a rehearsal, I assume that the clients will connect one after each other and stay on the server. So in most cases the connect logging will be sufficient. The question is: What would really help debugging the problem?

Maybe as a test the choir should first connect to a known good server, like on from Simons servers. The latency may be high but at least all the choir members can setup their audio setup so that the sound and level is ok. And then they will see how many choir members can be supported as a maximum. Then they can move to their own server. If that does not work, they know that either the bandwidth requirement or the CPU requirement is not met.

But I assume you have more experience with giving support for choirs using Jamulus. Do you agree with my arguments? Do you have other ideas how to improve the situation?

**Comment by storeilly** [comment]
You are welcome, I am also very grateful to you for your application.
My servers are similar to Simon's I've tried a few different config's 1/2/4 cpu's up to 15gb on AWS and GCP but with varying results across different versions. I have allowed other groups use them from time to time, but without knowing how many were on the server I can't judge the capacity limits of each config. Theoretically rehearsals have a group connecting at once(approx) and disconnecting at once(approx). I'm a tech head and will always look for the complete evidence.  With no disconnect time it is hard to know how long each connection remained. I've no problem converting event data into connection counts.
Thanks for the tip reg htmlstatus (haven't used that) and cron-ed top. I'll look into that.

**Comment by corrados** [comment]
> For stats & correlation purposes, isn't it better to capture useful info via regular cron-ed scripts like --htmlstatus file with some OS info at the same time? (ie htmstatus + top -b -n 1)
> [...] Thanks for the tip reg htmlstatus (haven't used that) and cron-ed top. I'll look into that.

Yes, this is a really good tip. That way you have the additional information about the CPU usage, too. Maybe you implement the script in a way that it checks the creation date of the htmlstatus file and only updates the log if the file date has changed (= the number of clients has changed).

**Comment by corrados** [comment]
> I have allowed other groups use them from time to time, but without knowing how many were on the server I can't judge the capacity limits of each config.

I have a much simpler solution for you:
```
2020-07-18 08:37:45, 127.0.0.1, connected (1)
2020-07-18 08:37:58, 127.0.0.1, connected (2)
2020-07-18 08:38:13,, server stopped -------------------------------------
2020-07-18 08:38:53, 127.0.0.1, connected (1)
2020-07-18 08:38:55,, server stopped -------------------------------------
```
You are just interested in the maximum number of connected clients. If you add the disconnection of the clients, you have to calculate the number of connected clients yourself which is not good. A much simpler solution is to add the total number of connected clients at the time when a new client connects. This is the maximum number. If a client disconnects it will not be logged but it does not matter since the number just gets smaller and never higher. It can only get higher if a new client connects.
The changes are trivial. I'll apply them today. This change is compatible to the ParseLogFile() function so this has not to be modified.

**Comment by storeilly** [comment]
Thanks, yes that is elegant and will fill that request perfectly. Thank you.

**Comment by Snayler** [comment]
Since a solution was reached, this can be closed.
