### ISSUE TITLE
Client use of Small Buffers can block frames to servers with version < 3.4.7 (2020-04-11)

### ISSUE THREAD

**Issue by pljones** [corrados/jamulus#317]
In my view, the client should "ask" the server whether it supports small buffers and only use them if it gets a "yes" back.

Currently it appears the new behaviour is forced on old, unsuspecting servers, which haven't a clue how to decode the truncated frames.

Users who are not aware of this behaviour (someone had to tell me...) think a server is blocked for _some_ reason that excludes audio frames.  (And, if you're like me, try to concoct all kinds of potential issues...  Didn't get this one.)

As this directly affects a user's experience in making music with Jamulus, I'd call it a bug - it's a lack of client-side backwards compatibility with older servers.

(The check box label will probably need changing to something less "strict" like "Request small buffers (when available)".)

**Comment by corrados** [comment]
There is a version check implemented in the client already for the Pan feature:
https://github.com/corrados/jamulus/blob/master/src/clientdlg.cpp#L775
We could apply a version check for the small network buffers easily, too.

**Comment by corrados** [comment]
BTW: I call it a feature request ;-).

**Comment by corrados** [comment]
Or better, let's call it an "improvement".

**Comment by pljones** [comment]
Fine :)

**Comment by pljones** [comment]
OK, so from looking at the source (`server.cpp` about line 598-600), just at the end of the new connection, the server says "Oh, and by the way, here's my version in case that affects the replies to the above requests" with CreateVersionAndOSMes.  Sadly, too late, as CreateReqNetwTranspPropsMes was the second message sent to the client.  I guess new clients can ignore CreateReqNetwTranspPropsMes and wait for CreateVersionAndOSMes to send the response?

**Comment by pljones** [comment]
Quick check: 42 servers connected (on Default Central Server, of course) with version < 3.4.7 as at 2020-07-06 (majority under Windows but with no particular geographic bias).

**Comment by corrados** [comment]
I am thinking more in this direction: See #149. Recently I have added a new registration protocol message: https://github.com/corrados/jamulus/blob/master/src/protocol.cpp#L292. This transmits the server version together with the other registration details. If we receive such a message, it would be easy to support a version check for the registration and, e.g., do not register servers which are older than, e.g., 3.4.7. That would solve the compatibility issue.

BTW: Looking at the other lists (i.e. not the Default list) you will find that the server versions are much newer. And the newest lists like Jazz or Rock only contain new server versions. So this issue seems to be only relevant to the Default list (which is always full and if we would block very old servers this would make space for other servers).

**Comment by pljones** [comment]
Yep - most people making their server public would go for a server visible to their version's client.  So when the client had Default and "Default NA", then people started registering with the NA server.  Anyone with an older version probably hasn't restarted it and almost certainly hasn't though to switch central servers from the default.  So those on the newer central servers _tend_ to be admins who upgrade their servers from time to time.

**Comment by pljones** [comment]
I'm going to close this as I don't think anyone who's still on such an old client should object to updating.  We've also got better at this backward compatibility stuff... :)
