### ISSUE TITLE
several small items

### ISSUE THREAD

**Issue by lefty665** [corrados/jamulus#458]
1 Please shorten connect button so it does not extend under the mute myself button.  That will prevent inadvertent disconnects (muting with a 'tude) when seeking to mute oneself.

2 Please add a limiter at something like 95 dB to prevent occasional excruciating bursts of noise.

3 Please add pedal steel & lap steel to instruments list

4 Please reorient the fader slider to horizontal to match left/right fading instead of vertical.

5 Note: having occasional severe unrequested change of input levels that can be restored by changing Jamulus settings, then reverting to original settings. For example changing from Normal quality to High quality then back restores original levels.

6 FYI, last evening we had a productive jam that spanned the US from East Coast to West Coast. It was really rather amazing. 

7 Thank you for a very useful app and for your ongoing development efforts. Y'all are putting a lot of work into Jamulus and as users we appreciate it.

**Comment by corrados** [comment]
1) Simple solution: Exchanging the order of the settings: On the top "Mute Myself", then "Settings" and then "Chat".
2) Jamulus basically clips at the maximum of "short" range. So there is already some limiting behavior implemented.
3) If you provide me with the pictures, I can integrate them. Please check out this Issue for details on adding instruments: https://github.com/corrados/jamulus/issues/131
4) Which fader do you mean? The local fader? I don't think it is a good idea to make it horizontal since we do not have enough space. Actually this fader is not meant to be a "pan" but in Mono-in/Stereo-out mode you change the level between your microphone and instrument. For that it does not matter if it is horizontal or vertical oriented.
5) "unrequested change of input levels" -> The input level changes suddenly? I did not observe such an issue yet on my setups. Which OS are you using?
6) The latency must have been large. This may work with slow songs but my personal limit is 60 ms. Above that I don't have much fun playing the drums.
7) You're welcome :-).

**Comment by corrados** [comment]
I just implemented 1). Here it is how it looks like now:
![grafik](https://user-images.githubusercontent.com/46655886/87592108-98b68700-c6e9-11ea-827e-73f44b661eac.png)
The distance between the disconnect and mute buttons is now large enough.

**Comment by gilgongo** [comment]
Seems we can close this now?

**Comment by corrados** [comment]
Yes, I agree. Let's close this one.
