### ISSUE TITLE
Logging and Graph causes failure on start up

### ISSUE THREAD

**Issue by pljones** [corrados/jamulus#493]
I run my server with logging and the SVG graph:
```
-l /opt/Jamulus/log/Jamulus.log -y /opt/Jamulus/log/history.svg
```
Since I updated my git code from master yesterday or the day before, I've had to trim the log to entries since July, or else the server fails trying to draw the graph, getting killed on start up.

I think it's hanging and systemd is spotting this because it's running realtime.  If I run it as a non-realtime process, it runs okay.

I'll investigate further unless someone knows why this could have happened.

(Perhaps the graph should be a separate thread...)

**Comment by corrados** [comment]
I am seriously considering removing the "history graph" from the Jamulus source code. I implemented this in the early development of Jamulus but it does not belong inside the actual Jamulus software. This is something for an external tool. Either a Linux script or some external app or executable. Since the history graph must not be real-time, it would be sufficient that the script parses the log file every, e.g., 10 minutes and plots a nice graph, e.g., using gnuplot. I have done this in another project, see: https://github.com/corrados/mypitools/blob/master/plotmyrunscriptdata#L17 You can get much nicer plots out of gnuplot and the user can easily modify the graph style etc. by simply changing the script. Right now the user has to use exactly what it gets back from Jamulus.

What is your opinion? Do you agree with me?

**Comment by WolfganP** [comment]
I agree. If the data files are complete and accesible, gnuplot is a great tool. Just enhancing the wiki with a couple of tested plot samples will complement Jamulus without diverting development efforts too much from the core (usually graphical or UI items get a lots of requests to accommodate different users needs/tastes, the gnuplot way allows empowering the user w/o core development needed).

**Comment by pljones** [comment]
Yes, it makes more sense to plot it externally.

I'd be happier letting the browser do it itself, these days:
- parse the logfile to JSON at the server (simple bit of perl/PHP/python)
- parse the JSON to SVG at the client (fairly simple JS, modelled on the existing SVG code)

**Comment by corrados** [comment]
Good idea, pljones. Do you want to write some scripts and add them to the Jamulus repository? Or would you prefer to create a new repositiory on Github just for this purpose?

**Comment by pljones** [comment]
I'll add them to the Jamulus.  Would something like this layout be suitable?
```
src/html/example_graph/index.html
src/html/example_graph/php/parse_log.php
src/html/example_graph/js/draw_graph.js
```

**Comment by corrados** [comment]
I would prefer to have a new directory for that:
**tools**
In that directory you should create another directory which explains the functionality, e.g., historygraph or webtool or something else (ideas?). So, e.g.,:
tools/historygraph/src/html/example_graph/index.html
or even simpler:
tools/webtool/index.html
What do you think?

**Comment by corrados** [comment]
Since you will provide the script, I'll soon start to remove the history graph from Jamulus.

**Comment by pljones** [comment]
`tools` is good.  I suppose the generic `webtool` allows for that mode of presentation to grow (see also the healthcheck / status stuff).

I already have the PHP parser (I was doing this already, except to support the date range):
http://jamulus.drealm.info/php/jamulus_history.php?lines=10
http://jamulus.drealm.info/php/jamulus_history.php?days=60

Now I just need to port the SVG code from C++ to JS... ... 😀

**Comment by corrados** [comment]
I created a new Issue for the graph tool: https://github.com/corrados/jamulus/issues/501
Since I now remove the history graph, this Issue can be closed since if no history graph is present in Jamulus anymore, it cannot fail anymore :-).
