### ISSUE TITLE
Channel pan

### ISSUE THREAD

**Issue by ilmastro79** [corrados/jamulus#52]
Hi!! Congratulations for the magnificent work done so far, this software is a salvation for us all!!
I'd like to share some ideas.
I wondered if by chance in the TODO list there is the possibility of:

- creating a pan knob/fader for each client/channel to optimize stereo listening
- vst efx implementation 

Thanks!

**Comment by tarmoj** [comment]
Hi, 
I have been working on this and the panning it is almost done. I need a bit more coding, testing and tiding up. Should I do a pull request or sending a diff is enough?
I hope  we have not done any parallel work on the same thing?
tarmo

**Comment by corrados** [comment]
Please no diff. If you want to supply code, a pull request is the right thing to do. But be aware that at the moment I am heavily changing things in the Jamulus software.

**Comment by tarmoj** [comment]
Yes, I got it working -  now in my local build directory pulled from github. I created another branch "panning" and merged there the latest changes from master. 
I will fork now the repository, double check and will make the pull request probably tomorrow.
Do you use QtCreator for development? What is set for you identations (tabs, spaces?), it seems to me I have something different, so it is probablt best to align it with you.
tarmo

**Comment by corrados** [comment]
QtCreator, tab length=4, insert spaces.

**Comment by corrados** [comment]
The current Git master contains the support for panning -> closed

**Comment by corrados** [comment]
I just updated the Central Server for the new panning code. If you compile the latest git master code and connect to the Central Server, you should now see this:
![grafik](https://user-images.githubusercontent.com/46655886/82532647-1aeb5a80-9b42-11ea-85c2-052200576f47.png)

**Comment by tarmoj** [comment]
Great, thanks!

On first  quick try it works as expected, did not have chance to test with
several clients though.

I aslo put up a new private server of this version up for testing to
live.uuu.ee

Best!
tarmo



Kontakt Volker Fischer (<notifications@github.com>) kirjutas kuupäeval N,
21. mai 2020 kell 10:05:

**Comment by slimvince** [comment]
Hi! Will this panning feature also work for letting others separately pan any client´s two individual mono feeds (rather than assuming it is a true stereo mixdown)?
Let's say I sing AND play a mono electric instrument feeding L and R respectively.
Other clients will want to pan my voice and instrument independently.
regards
Vincent

**Comment by tarmoj** [comment]
Hi,

Since I wrote the base of this code I think I can answer:

No, if you send stereo and different signals (like voice and guitar) are in
L and R, there is no way for other users to separate it to two independent
channels that can be panned. They can apply panning to your signal but it
makes no sense since if you move away from the center one of the two gets
softer, there is not really a stereo effect.
What should work - I believe -    if you have enough internet bandwidth, is
to have two Jamulus apps running, make both work in mono in/stero out mode
and take one input (like song) to one app and other to the other.
OR: you can use one app in mono in/stero out, but then your voice and
guitar will be mixed together (and they move in the panning together).

Hope it answers your question.

Best!
tarmo

Kontakt slimvince (<notifications@github.com>) kirjutas kuupäeval R, 22.
mai 2020 kell 13:14:

**Comment by slimvince** [comment]
Thanks for your swift reply!

I have already tried (and verified) that running two client instances works fine...(for us tech-savvy at least) 👍 

Maybe it could be a feature request to remove the assumption that clients are always stereo or mono rather than dual mono? This would also let clients decide **both** level and panning for everybody elses feeds, not just level,

**Comment by diegodlh** [comment]
In our choir rehearsals we use "Mono" mode to minimize bandwidth requirements.
It would be useful for us if each singer could distribute the voices of their colleagues from left to right. However, the per-channel pan wheel is disabled in "Mono" mode.
Wouldn't it make sense to have it enabled anyway? This way, one could choose where to place each mono channel in a left-right spectrum.
If you don't see any reason against this, I can submit a new issue or reopen this one, as you prefer.

**Comment by tarmoj** [comment]
Hi,

Sorry, I remembered that probably noone answered yet.
You need to use mono in stereo out mode, this saves somewhat network bandwidth more than just stereo. As panning happens in the server, you need to receive stereo signal, panning in plain mono is naturally impossible.
Best!
tarmo

**Comment by diegodlh** [comment]
Hi, Tarmo.

> You need to use mono in stereo out mode, this saves somewhat network bandwidth more than just stereo.

Actually mono-in/stereo-out mode sends a stereo signal to the server as well, as discussed in #531, so no network bandwidth is saved as compared to stereo mode.

> panning happens in the server,

I assume pan controls in the personal mix (which I referred to as "per-channel pan wheel" above) happen client side.

> panning in plain mono is naturally impossible.

I don't agree with you here. I think distributing incoming mono signals from left to right might be useful, and I don't think that is "naturally impossible". For example, [Wikipedia entry on "Panning"](https://en.wikipedia.org/wiki/Panning_(audio)) says "Panning is the distribution of a sound signal (either monaural or stereophonic pairs) into a new stereo or multi-channel sound field determined by a pan control setting."
