### ISSUE TITLE
jamulusjazz.fischvolk.de:22324 appears to be down

### ISSUE THREAD

**Issue by gilgongo** [corrados/jamulus#524]
As of about 12 hours ago perhaps?

**Comment by corrados** [comment]
It's fixed now.

**Comment by corrados** [comment]
The Jazz Central Server is not my own server. We had a maintanence last night and it seems the server did not restart correctly afterwards. Since it was not my own server, I could not repair it.
What I did this moring was that I started another Jazz Central server on my own Virtual Machine and changed the URL record to point to my own server. This record change does take a while to be distributed in the network. On my own PC I still cannot see the list but the Jamulus explorer already sees it now: http://jamulus.softins.co.uk

**Comment by corrados** [comment]
@pljones It has shown that your Central Servers are very reliable in the past. Do you want to take over the Jazz list as well? Then you have three lists under your control.

**Comment by pljones** [comment]
Sure - I've set up another Central Server, running on 22324 (and remembered to put the firewall rule in place, this time).

**Comment by corrados** [comment]
Great. Is it already completely setup and ready to run? If yes, then I will change the DNS entry to point to your server.

**Comment by pljones** [comment]
It should be - jamulus.drealm.info:22324 should get you in (best someone "outside" checks).

**Comment by corrados** [comment]
I just tested it. It works fine. So I will change the DNS entry now.
