### ISSUE TITLE
Integrate sound check

### ISSUE THREAD

**Issue by ann0see** [corrados/jamulus#534]
As mentioned in #532 one of the most challenging things if you setup jamulus for the first time is the audio setup (especially on Windows with ASIO4ALL).

I would suggest to integrate some kind of audio check which can be run on the first setup of jamulus or on a change of your audio devices. This should run locally to ensure that issues are not due to connectivity problems. Moreover the audio check should not automatically start but maybe be linked if you are not connected to a server e.g. in the box where the audio sliders are if you‘re connected to a server on the right in the main view.

The audio check should mirror sound from inputs to headphones and give advice or link to the troubleshooting wiki what to do. 

Usually problems are due to wrongly set input/output devices, background programs running and occupying the soundcard,...

**Comment by corrados** [comment]
For me this calls for an external tool. Maybe something like that already exists (maybe even open source)? Every audio application which uses ASIO should have the similar problem.

**Comment by ann0see** [comment]
That’s quite a point. I also don’t think it’s mainly a jamulus issue. The problem is on the user side.

One user (more specifically quite a few) I helped setting up jamulus and fixing the audio were very frustrated after starting jamulus for the first time and not being able to hear/play. They didn’t know how to fix it (and didn’t find any solution or guide). I assume the main problem is ASIO4ALL but I don’t think anything can be changed there. 

Maybe we could also just add a link to the troubleshooting wiki if jamulus detects ASIO4All.

**Comment by gilgongo** [comment]
Now that we have a [basic guide](https://github.com/corrados/jamulus/wiki/Installation-for-Windows#setting-up-asio4all) to setting up devices with ASIO4All, at least that can be referred to. Whether we'd want to have a link under the button in the client is another matter though. We do have a link to the Getting Started page in the menu, but I don't know how often people see or use that.

**Comment by ann0see** [comment]
>  but I don't know how often people see or use that.

I don't think many actually look there. What I'd suggest is to also link the troubleshooting section and possibly add a checkbox to the installer on Windows to automatically open the wiki or a README file. Or we could add a message in jamulus asking if the user wants to have a look at the wiki to get help and that the wiki/troubleshooting page is linked under "help" in the menubar if it detects that it hasn't run before (does an ini file already exist on the first run?)

**Comment by gilgongo** [comment]
Well, if we think they don't look at the help in the menu bar, then adding a troubleshooting link would seem a bit futile :-) But I have no evidence either way. For all I know, the menu bar links could be getting lots of traffic, so we could add that link.

There is a bit of a tradition of "first-run help" windows which immediately get closed, even by quite un-confident users. This seems to be because people generally want things to be easy and will subconsciously give apps a chance to be so. It's only later they tend to seek out help when problems arise. I think by that logic your idea of an in-context help link near the ASIO setup button may be better really.

Also, one thing that might help is to try to make it a bit harder to download Jamulus without going through the wiki. Right now, we provide direct links in some paces to the SF download. I get the impression some people may be unaware of the wiki because of this, and turn to Google, which unfortunately provides out of date or confusing information complied by others over the years. The wiki has been constructed from the "start here" link on the first page to give people some clue as to what using Jamulus entails before they download it (and you'll see the server side of the wiki actively tries to discourage server setup without sufficient knowledge).

I was recently reminded that the [survey](https://docs.google.com/document/d/11fSDoSfp5w40VixXabujyzarV-wDYIapftyF-Dhc6I8/edit?usp=sharing) we did (which I keep telling myself I should re-run now that the initial Covid-induced usage spike has passed for Jamulus) said that while about 62% of respondents described themselves as having "advanced" computer skills, only 30% said they felt they knew what to do in the event of problems (BTW you are correct about the sound card issues: 42% currently say that's the most difficult thing. Also BTW since the summary was taken, 2% have identified themselves as having "basic" skills).

**Comment by ann0see** [comment]
The results of the survey are quite interesting. I‘d say that maybe the wiki should be more in focus (e.g. as you suggested, the Getting Started entry should be linked more often)

**Comment by ann0see** [comment]
Just came up with an other idea which is probably not wanted.

We could integrate a „ultra simple mode“ which guides the user through jamulus setup:
Installation>Assistant Window opens>Checks if you have an ASIO driver installed. Yes: show a green light/ok
>No: Show a red light and link to wiki
Next step:
Configure your ASIO driver:
Tell user to click on connect & connect to a free server next click on settings; leave assistant window open. If user has done this and it’s ASIO4ALL show link to Wiki and tell him to do a sound check on the server (play some cords/sing/...) and check if he can hear himself. Link to wiki.

**Comment by gilgongo** [comment]
This is really a problem for somebody who knows more about the technical possibilities on Windows I think. I mean you could imagine a setup screen that presents a list of available audio interfaces on the system that support Jamulus (that is, they have the required buffer sizes and things) and then does some kind of magic to set the desired one up before launching the client in perhaps a default stereo mode. 

Otherwise, right now we don't know what the appropriate audio devices on their system are even called, and can only really say "enable/disable the correct inputs/outputs".  They also might have proprietary ASIO drivers for their device, so we don't want to confuse them by referring to things they don't have.

It's pretty tricky, and risks creating more support problems than it fixes I think.

**Comment by ann0see** [comment]
That’s a point. 
A bug I have experienced twice and which could probably be a common issue after the first installation if Jamulus was that although ASIO4ALL was correctly configured there was no sound. A restart of Jamulus fixed the problem.

Also something else: ASIO4ALL showed beyond logic eventhough there was no obvious app running. This could only be fixed by a few Windows restarts.

**Comment by ann0see** [comment]
By the way: I updated the windows compile page in the wiki to link to the Steinberg ASIO SDK. I hope that's the right link? 
Furthermore I think llcon.sourceforge.net should be updated (and mostly link to the GitHub Wiki since having two pages to update in my opinion is just unneeded work). I'll open an issue on that.

**Comment by ann0see** [comment]
I think this issue in general is broader. 
What I see as the main problem is the difficulty of setting up ASIO4All.

I will close this issue in a few days/hours and suggest to open a separate issue to discuss how to make the audio setup easier. 
A lot has already been done (especially in in the wiki).
