### ISSUE TITLE
Server on command line shows Recording state not initialized if recording is not used

### ISSUE THREAD

**Issue by corrados** [corrados/jamulus#536]
@pljones When I start the Jamulus server without using the -R feature, it shows "Recording state not initialized". I find this confusing. It would be better to suppress this warning. Do you agree?

**Comment by pljones** [comment]
I'd prefer GUI-less start up to report the full state of all settings, myself, whether from direct command line options or loaded from an ini file.  That way they would be logged.

There's less value to me in being told about settings I actively made than in learning about those made due to my lack of action.

**Comment by pljones** [comment]
OK, I'm going to link this to #574 as that would mean you'd either see "enabled" (because of existing behaviour) or "disabled" (because of the new flag).

In implementing #574, I'll make sure redundancy of the messages doesn't happen.

Currently, you'd start, get told "enabled", then send SIGUSR2 and get told "disabled".  Passing the new option must prevent the existing "enabled" and display only the "disabled" - then SIGUSR2 would cause "enabled" to be displayed.

**Comment by corrados** [comment]
Ok, so I‘ll close this now.
