### ISSUE TITLE
Status indication for Central Server registration

### ISSUE THREAD

**Issue by gilgongo** [corrados/jamulus#55]
So that operators can know whether to expect to see their public server listed by the Central Server, show a registration status indicator in the UI (example below).

**Note**

Because we currently have a number of people on the forums whose problems may in fact be due to their server not being registered due to [this issue ](#50 ), **it is important to message explicitly the "Registered" and "Unregistered" states** to avoid the possibility of users misinterpreting silence as being all is well, when in fact they are unregistered (or vice versa). 

Ideally, a state of "**Connecting...**" (or "Registering..."? But I think that might be misinterpreted) should also be displayed to help troubleshoot other issues if the server cannot contact the Central Server.

![image](https://user-images.githubusercontent.com/4561747/79041298-a6d6a200-7be6-11ea-8d36-8b88166e92dc.png)

For headless servers, a similar message to be displayed in the log _(platform dependent?)_

**Comment by pljones** [comment]
I've yet to look at the code for this.  So I could be quite, quite wrong...

Remember, Jamulus is _connectionless_ - anything that _looks like_ a connection is just persisted data -- which can go stale.

I think when the server registers with the central server, it gets asked whether it's still alive every so often.  Receipt of this message would let the server know that it is, indeed, registered.

If the server stops getting the pings, several things could have happened, basically resulting in those pings not arriving.  Both server and central server could still be running, though.

Indeed, a client asking for the server list from the central server might not see the server any more, despite it running (and having once been registered).

So the server needs to decide how long to wait for a poll from the central server before deciding something is wrong.

What it can't do is decide what is wrong.  Has someone broken the local router?  Has something happened to the local ISP?  To the central server's ISP?  Has the central server crashed?  Or something else?

So the best it can do is go into that "waiting..." state again.

Again, I _think_ the server keeps trying, once its been told to register.  Eventually, when the response starts arriving again, it can return to Registered.

**Comment by gilgongo** [comment]
BTW although this isn't directly related to the ticket, I think we should consider changing the current wording of _"Register My Server in the Server List a the Central Server"_   to _"Make my server public"_  

This would make a better connection between the vocabulary in [the documentation](https://github.com/corrados/jamulus/wiki/Choosing-a-Server-Type) and what people see in the UI.

**Comment by corrados** [comment]
Let's wait for my implementation of Central Server regions. If we have enough space on that servers we do not need that indicator at all. We only run into issues since the server list is full. That should not be the case in the future with many Central Servers.

**Comment by gilgongo** [comment]
Although in theory the 200 server limit isn't the only cause of registration problems, so knowing for (almost) sure whether a server is registered or not is useful, no?

**Comment by corrados** [comment]
Yes, but of low priority.

I assume that the server list registration fails in 99 % of the cases because the server list is full. We should monitor the feedback of the users in the Discussion forum if I am right with my 99 % assumption after I have released a new Jamulus version supporting the second Central Server. If we still hit the 200 limit for the two Central Servers, it will be easy to create another region until the limit will no longer reached in any Central Server.

**Comment by corrados** [comment]
> I think we should consider changing the current wording of "Register My Server in the Server List a the Central Server" to "Make my server public"

What about: "Make My Server Public (Register My Server)"?

**Comment by gilgongo** [comment]
Yes that would be even better as some conversions on the forum use the "Register" word.

**Comment by corrados** [comment]
Ok, I add the server list, too, so that it now will be: "Make My Server Public (Register My Server in the Server List)".

**Comment by gilgongo** [comment]
" in the Server List" is possibly a bit unnecessary - do we think people would think it would be registered somewhere other than on the list? Might be a bit long too,

**Comment by corrados** [comment]
We have the space so I would keep it. It does not hurt to write it I think.

**Comment by corrados** [comment]
Related to this: I implemented a nice new feature in the client: If the user clicks the Connect button and no answer is received from the server, a label shows that we are trying to connect (so that it is clear that we are currently not connected), see the following picture:

![grafik](https://user-images.githubusercontent.com/46655886/79074935-a4ac3a80-7cef-11ea-8a80-13398d6d8f61.png)

**Comment by pljones** [comment]
Nice and clear.

Does this get displayed if there's a "break" when nothing is received, even after the first "connection"?

**Comment by corrados** [comment]
Just the first connection, but this should cover 99% of the usecases.

**Comment by gilgongo** [comment]
Very nice - feedback is one of Don Norman's [six principles](https://www.csun.edu/science/courses/671/bibliography/preece.html)!

**Comment by pljones** [comment]
I think the quickest way to get the server registration status would be for the server to ask the central server it registered with for the server list - the downside is it's a big response for so little information.

(Tangentially, I was wondering what the overall impact is of a very large number of clients having the "Connection Settings" window open - just sitting there polling every server every couple of seconds - quite a lot of traffic for those servers to deal with.)

**Comment by corrados** [comment]
Yes, and we should still have the goal to keep every network traffic as low as possible. This has gained importance due to the fact that the server list is so filled up.

**Comment by pljones** [comment]
Staying on my tangent a moment - although the changes to the Connection Settings window go some way to helping for usage...

I was thinking of having a staged fall back in ping rates - green servers are kept "more fresh" than amber or red ones progressively.  Initially ping all the servers to establish a "fairly reliable" ping distance, then something like ping every 2 to 5 seconds the green ones (progressively longer interval depending on rising ping), 5 to 20 seconds for amber and 20 to 60 seconds for red.  (To me, there's almost no point pinging the red ones other than to establish they're really there so even once a minute might be a bit too much.)

Anyway...  For the confirmation of server registration, perhaps send back a "registation request" to the registering server as confirmation?  Old servers would ignore it (they aren't central servers), new servers would consume it as the indication they'd been looking for (registering again if it hadn't been received within some timeout lower than the current 15 minutes).

**Comment by corrados** [comment]
That would also be a "connection less" message. So it is unreliable. But in most cases it would get through. But if you choose a short time out for the initial phase, let's say if the "registration accepted" message was not received in 1 minute, try again. If after, let's five times the registration did not get the accepted, we simply stay with the 15 minutes rule as is implemented right now. The Central Server could then also return a "registration failed due to list is full" message so that the server immediatly knows what went wrong and could stop the registration for now. Maybe then continuing to try after the 15 minutes.

**Comment by corrados** [comment]
Regarding the Connection Dialog: This dialog was not meant to stay open for a long time. You simply open the list and choose a server.
One could reduce the ping period for servers with long ping time. But you would not gain much and we get more complicated code. I would not want this actually...

**Comment by pljones** [comment]
Connection Dialog: OK, perhaps just have the whole list fall back to once a minute once the initial "reliable ping" time is established?  That lets people leave the window open whilst jamming on one server but keeping an eye on what's happening elsewhere without putting too much load on the network.  (I think this might be a common use case, in fact.)

Registration Confirmation: Are you suggesting a new protocol message, then - "registration response"?  That would probably simplify things, rather than trying to reuse existing messages.

**Comment by pljones** [comment]
Here's the protocol, plus Central Server change - not a pull request yet, as I've got as far as "it compiles", no testing...

https://github.com/corrados/jamulus/compare/master...pljones:feature/55-server-registration-status?expand=1

**Comment by pljones** [comment]
OK, let's call that working -- without retries at this point.

Server UI has "Unregistered", "Registered" or "Central Server full" status, depending on whether it's not tried or tried and had no response (I don't differentiate yet), had a good response or had a "full" response.

I can add the retries later.

**Comment by corrados** [comment]
I put some comments in your code.

**Comment by pljones** [comment]
I've updated - I'll raise the PR now.

**Comment by corrados** [comment]
The code is ready and merged: https://github.com/corrados/jamulus/pull/87

**Comment by corrados** [comment]
This is how it looks like:
![grafik](https://user-images.githubusercontent.com/46655886/79630962-fa506f00-8155-11ea-87ef-b78d0f1c4771.png)
![grafik](https://user-images.githubusercontent.com/46655886/79630972-0805f480-8156-11ea-90c5-cb4fada7bbf2.png)
![grafik](https://user-images.githubusercontent.com/46655886/79630983-19e79780-8156-11ea-86a6-012ba7c67ce7.png)
