### ISSUE TITLE
Don't scroll Mixer Level vertically when scrolling User list horizontally

### ISSUE THREAD

**Issue by chrisrimple** [corrados/jamulus#617]
Problem:
With 15+ users on a server, horizontal scrolling is necessary to see all Users in the Jamulus Mixer window.  While scrolling horizontally, sometimes an individual User Mixer Level will scroll vertically.  This seems to be a side effect of the click region for the User Mixer Level control, which may extend too far down vertically, so that it overlaps (or is very close to) the User Names click region.

Additional Notes:
This may be limited to Macs or laptops with trackpads only.

**Comment by corrados** [comment]
> While scrolling horizontally, sometimes an individual User Mixer Level will scroll vertically.

If you click on the horizontal scroll bar and move the mouse, your movement should only apply to that scroll bar. Just if you release the mouse button and click again, you might move the faders. Is that what you mean?

Or is this an issue with using the mouse scroll wheel?

Anyway, this is something I will not be able to change easily since this is the Qt functionality. The regions where the GUI control accept scrolls is defined by Qt and I think I cannot simply change this.

As a workaround, have you tried the Settings->Skin->Compact? This is specifically desined for large groups of musicians. If I make the Jamulus window quite large in that mode, I can easily see about 30-40 faders without scrolling (but I have a large monitor, too ;-) ).

**Comment by chrisrimple** [comment]
I don't have this experience if clicking on scroll bar with mouse and dragging - it only happens when using a touchpad or maybe a mouse scroll wheel (Mac Magic Mouse), where the user is dragging two fingers to scroll horizontally and vertically WITHOUT first clicking to select the scroll bar.  Possibly no fix, if an OS function.

Haven't tried the Compact skin, but will check it out.  :)

**Comment by corrados** [comment]
> With 15+ users on a server, horizontal scrolling is necessary to see all Users in the Jamulus Mixer window.

The next Jamulus version will include support for two rows of faders. Together with the Compact skin, this should solve the problem for you since you do not need to horizontally scroll anymore.
