### ISSUE TITLE
Can We Have Mute Myself Locally Shut Down Audio Going From Client To Server

### ISSUE THREAD

**Issue by maallyn** [corrados/jamulus#640]
Folks;
I understand that the Mute Myself button tells the server to mute my signal from the mix going to each of the other clients.
If the server is busy, there is a delay between you clicking on the Mute Myself button and my sound actually removed from everyone's mix.
Can this button instead simply do something locally to prevent my sound from going from the client to the server immediately instead of just signaling the server to stop my sound from being included in the mix going to each client?
I had an event where I was on a stage and suddenly I needed to cough. I clicked on the mute myself button. However I noticed my sound still coming back to me on my mix. It took about three seconds to be finally muted. I ended up disturbing the stage.
Thank you
Mark Allyn

**Comment by corrados** [comment]
> I understand that the Mute Myself button tells the server to mute my signal from the mix going to each of the other clients.

No, this is not the case. The Mute Myself works at the client so it immediately suppresses the audio data as soon as you press the button.

> I had an event where I was on a stage and suddenly I needed to cough. I clicked on the mute myself button. However I noticed my sound still coming back to me on my mix. It took about three seconds to be finally muted. I ended up disturbing the stage.

Unfortunately, we cannot do anything about this. You cannot change network audio packets after you have sent them over the network. So, what happens when you press the Mute Myself button is that immediately, all audio packets leaving the client are muted. But at that moment there are a lot of previous audio packets on their way to the server and also from the server to all clients. This latency you will not be able to shorten.

**Comment by maallyn** [comment]
Thank you for the clarification. Shall I go ahead and close?

**Comment by corrados** [comment]
I fear I cannot do anything to improve the situation. So, yes, I'll close this issue now.
