### ISSUE TITLE
Do we need to document settings files?

### ISSUE THREAD

**Issue by gilgongo** [corrados/jamulus#654]
What is/are the use cases for editing settings files for the client and server? 

I'm a bit wary of over-documentation in case it confuses people, but there was a ticket (can't find it now) where we wondered if we should document where Qt stores settings files on each platform. I'm unclear what the need for that is though (and I don't know what the docs should say if we decide to have them).

**Comment by corrados** [comment]
Do you mean this one: https://github.com/corrados/jamulus/issues/198? This is already closed.

**Comment by gilgongo** [comment]
So I think the answer to whether docs are needed is probably 'no' in that case, although there does seem to be a use case implied while we have the `--inifile` option. Hard to say. Closing though.

**Comment by pljones** [comment]
`--inifile` doesn't imply you need to know how to create an inifile, just where you want one stored.  Mostly it lets the GUI client have multiple instances with separate settings easily (e.g. mic and keyboard clients separate, so that they can be mixed separately in Jamulus - useful particularly for situations like the WorldJam).
