### ISSUE TITLE
Server names list ordering feature

### ISSUE THREAD

**Issue by trebmuh** [corrados/jamulus#66]
Hi all.

The different lines in the server names list (see below) are moving fast which is hard when you're searching for a server name, or in which server your musician mate is, or where is the server,...
![servername-list](https://user-images.githubusercontent.com/8705846/79121255-2ace8c80-7d95-11ea-969f-fd97b03bd80d.png)

It would be great if a user could be able to sort the list:
- by alphabetically "Server Name" order when clicking on the "Server name" row/column case
- by ping time order when clicking on the "ping time" row/column case
- by number of musicians when clicking on the "Musicians" row/column case

I'd suggest next to split the Location in 2 columns, one for the country, one for the city. Then it would allow to order the list by Country or by City clicking on it too.

I hope this make senses and it helps.
And moreover, thanks for this very nice piece of software, you guys deserves a lot of kudos for that!

_Using 3.4.7 on linux debian buster here._

**Comment by corrados** [comment]
Many users do not really understand the importance of the ping time. The ping time is essential for jamming. Therefore it does not make sense to let the users choose the sorting.
But I have good news for you. If you are on Linux, you will most probably be able to compile the latest Git code. I have done some modifications for the --showallservers mode where you now can sort the list by clicking on the headers. Also you get the registration number shown for each server. This is very useful for debugging problems with the server list. Since the --showallservers is an inofficial command line argument and it is intended for debugging, of course, the sorting makes sense for this tool.
I hope this helps you.

**Comment by corrados** [comment]
I have a better idea. I did some initial testing and come up with a "filter":
![grafik](https://user-images.githubusercontent.com/46655886/79159099-c7198300-7dd7-11ea-8723-252e30b4bd99.png)
How do you like this?

**Comment by corrados** [comment]
I came up with a different idea: A possibility to filter the list:
![grafik](https://user-images.githubusercontent.com/46655886/79159249-03e57a00-7dd8-11ea-9464-99e77f20a074.png)
How do you like that?

**Comment by trebmuh** [comment]
That is a very good addition!

**Comment by vocobox** [comment]
I would find convenient to have the tree closed, i.e. not seeing the musican names at the beginning. Then if I enter a musician name in the filter,  the tree is opened and filtered to limit the server list to the server where this musician is currently playing.

**Comment by corrados** [comment]
The filter option is now added to Git: 514bd25fee8bc848b3b068ef95e5b50795e9af06. If you can compile the code it would be great to get some feedback on the new functionality.
Regarding the trees open/close, I will take a look at this.

**Comment by corrados** [comment]
I have added a new feature:
![grafik](https://user-images.githubusercontent.com/46655886/79242654-e0244180-7e74-11ea-9869-f157cd96bf7b.png)
It is contained in Git in the following commit: a0f7ee4627a15d17f7c40d87cda2189bfadfe265
I will close the issue now. If you are still not satisfied, then simply re-open the issue.

**Comment by trebmuh** [comment]
@corrados just rebuild from master c280e99 and it works as a charm. Thank you very much, it is awesome!

**Comment by vocobox** [comment]
Hi, it's working perfectly! The "show all musician" is actually better than my tree open/close suggestion, so forget it :)

**Comment by corrados** [comment]
Great, thank you for your feedback :-).

**Comment by jujudusud** [comment]
@corrados , I also just build the master c280e99 on Archlinux. Ok for me and a very good new filter feature. Thanks a lot for all that stuff.

**Comment by vocobox** [comment]
Hi,

The new UI is great, but its behaviour can be improved. 

The below scenario shows why it is not optimal when you are looking for a specific server. I am personnaly looking for a server rather than a musician, so maybe it is a personnal need. 

Said short, I suggest that the "show all musician" is **OFF** by default rather than **ON**.

Current behaviour :
1 : the server list starts loading with "show all musician" **ON**. But musicians are not loaded yet
2 : I start looking for a server, then I try clicking a server
3 : musician list of each server arrives to the client, so GUI changes. I can't click anymore, so I toggle "show all musician" **to OFF**.

Prefered behaviour :
1 : the server list starts loading with "show all musician" **OFF**.
2 : I start looking for a server, I try clicking a server and it works since no new incoming element will expand the tree :)
3 : If I am looking for a musician, I toggle "show all musician" **to ON.**

**Comment by corrados** [comment]
This is already in the pipe. I will store the Show All Musician in the init file. Then your preferred setting is restored everytime you open the server list.
