### ISSUE TITLE
Make Jamulus client and server icons distinct

### ISSUE THREAD

**Issue by marktheharp** [corrados/jamulus#700]
Hi all – I’m using Windows, and the Jamulus client icon and the Jamulus server icon look exactly the same. They are both on my taskbar and I sometimes select the wrong one. More importantly I have colleagues I talk through the software and they get confused as well. Can the server one be changed in some way – maybe with a red dot on it or something similarly simple and symbolic?

**Comment by gilgongo** [comment]
I've always wanted to use that old Apple "restaurant" icon... :-)

![image](https://user-images.githubusercontent.com/4561747/97433632-b82e9400-1915-11eb-86e9-ab2abb0656ab.png)

**Comment by pljones** [comment]
The Windows Installer, Mac packages and Linux desktop files can reference separate icons easily enough.

Run time is `QWindow::setIcon()` or `QWindow::setWindowIcon()` - so if the desktop server runs, it can switch which icon should be used and then the right icon can be set each time a window is opened.  That would need a bit of looking into...

**Comment by gilgongo** [comment]
> Hmm... I'd prefer something with a mixing desk icon :)...

Given that the client quite literally presents itself to the user as a mixing desk, that's a wonderfully "system centric" icon preference :-)  But maybe it means we should in fact have different icons for client and server, and preserve the "cloud" icon for Jamulus as a whole?

**Comment by HughePaul** [comment]
I recon something that looks like a server rack icon in a cloud. dual benefit of looking both like a server and mixing outboard.

perhaps something along these lines?

![jamulus-server](https://user-images.githubusercontent.com/128149/97553436-53367500-19cd-11eb-83eb-35357f9623db.png)

**Comment by gilgongo** [comment]
Yes that probably fine. All we need to do is differentiate after all.

**Comment by pljones** [comment]
> Given that the client quite literally presents itself to the user as a mixing desk, that's a wonderfully "system centric" icon preference for the server :-)

True, true... I did think of that after I'd posted...

> perhaps something along these lines?

My server doesn't look like a rack ;)  But then, my client doesn't look like an electrical discharge...

> Yes that probably fine. All we need to do is differentiate after all.

Agreed - so long as there's not too much detail that the icon is unidentifiable between the two, it's okay.

I'm still unsure how to make it actually happen, though.

**Comment by corrados** [comment]
Why not just use a different color? Maybe use red color for the Jamulus server and the normal blue color for the client.

**Comment by corrados** [comment]
But maybe @geheimerEichkater should comment on that because he is the creator of the icon.

**Comment by gilgongo** [comment]
Ideally,  color alone should not be used to convey meaning, so if the issue here is that people are confusing the two icons, then color and something else should be used in order to have an accessible solution.

**Comment by marktheharp** [comment]
– Thanks all for discussing this. That’s why I was suggesting the red dot – so even if you’re visually impaired and can’t see colour, you can still see that the server logo looks a little bit different.

**Comment by corrados** [comment]
I would like to keep it simple. Putting an "S" instead of the flash or a "red dot" would be my preferred solution. But I would like to wait for geheimerEichkater to get his feedback (I hope he follows this discussion).

**Comment by marktheharp** [comment]
Of course – good suggestion. I was also thinking though, of an international audience hence symbols.

**Comment by geheimerEichkater** [comment]
Yes! 
So my initial designs (back then) had omitted the lightning bolt in the icon in favor of the Jamulus-"J", but we decided to keep the bolt alive for some transitional period. Maybe we can make use of the situation now to progress further and also clean up the ambiguity:
1) the client icon as a consumer icon, friendly blue/white as is, a "J" replacing the bolt
2) the server icon for the "pros", highest contrast color theme (black/white instead of blue/white) with the Jamulus-"J" and a superscripted "S" to follow. Could instead also be a dot, an asterisk, whatever seems less confusing, but I thought the "S" will do? Also added stylized net(-work) extending from the cloud.
Pls see attached screen shot below.
<img width="722" alt="icons" src="https://user-images.githubusercontent.com/67019343/97800466-ab6fb000-1c35-11eb-8238-b1958134553d.png">

**Comment by pljones** [comment]
Maybe not a "J", as has been mentioned a symbol might be nicer.  Perhaps a single musical note on the client with "*" or maybe a trill for the server.  (And I liked the old colour scheme, so I was wondering if that could be used server side.)

**Comment by corrados** [comment]
I actually do not want to change the icon for the Jamulus client. Please just create a new one for the server.

**Comment by marktheharp** [comment]
Absolutely – it makes total sense just to have the server one different. I love the little networking things poking out of the cloud in geheimerEichkater’s idea. Almost look like sun rays! But just keeping the lightning bolt thing for both?

**Comment by geheimerEichkater** [comment]
Ok, so only the server-version-icon, preferably distinguishable through form and color. I would advice against going for a solitary "S" since that doesn't connect to the product name at all. The bolt is established and hence suggests the connection of both apps at first glance. So I adapted the bolt, kept the "network", kept the black color. Also, since @corrados mentioned a red dot, I colored the bolt … red (not too convinced of the red though). I think now they portrait two aspects of one service, at the same time being distinguishable through form and color, regardless of displayed size or background.

<img width="700" alt="Bildschirmfoto 2020-11-03 um 18 24 48" src="https://user-images.githubusercontent.com/67019343/98020492-5ed9cf80-1e03-11eb-8e4d-6fd0fbb6bedf.png">

**Comment by ann0see** [comment]
What about the red we use on jamulus.io? See the fw.css file class .red?

**Comment by marktheharp** [comment]
Hi – I like this. As it was me actually, who suggested the red dot, I just want to clarify that I was thinking of the red dot as being to the left of the lightning bolt, not attached to the end of it, and also a bit larger than the one in the illustration. That way even if you are colourblind, or the logo is quite small, you will see a difference

**Comment by corrados** [comment]
I also like that new proposal. I'm fine with using that one.

**Comment by corrados** [comment]
@geheimerEichkater Let's use your proposal in https://github.com/corrados/jamulus/issues/700#issuecomment-721276538. Can you please create a Pull Request where you add a fronticonserver.png and the corresponding .ai file? Then I can integrate it in the Jamulus server dialog.

**Comment by marktheharp** [comment]
That’s cool – I would ideally have preferred - see my original post as I started this thread! – To have the red dot on the side of the lightning bolt but it’s great that it will be addressed in some form. Thank you.

**Comment by corrados** [comment]
Thank you, geheimerEichkater, for the new icon.

The new icon is now applied to the server dialog on Git master -> closed.

**Comment by corrados** [comment]
@geheimerEichkater I need the Windows and Mac icon format for the new Jamulus server icon as well. Can you please create these?

**Comment by marktheharp** [comment]
Thanks for reopening this. As commented elsewhere, this is what I imagined when I originally posted the idea of a different symbol - adding a red dot to it. I think that would work for colourblind people as well. I should really have created a mockup so here is it. The proposed is "ok" but if this icon is to be revisited I think this is better and would work for colourblind people too:
![jamulus](https://user-images.githubusercontent.com/22644606/99973698-f34aa880-2d97-11eb-89cc-1cbefe0665bb.png)
I have two Windows 10 machines (all latest updates) and on both of them with 3.6.1 my machines still show this in the taskbar: 
![jam 361](https://user-images.githubusercontent.com/22644606/99973779-0a899600-2d98-11eb-94e9-95eeca9f2d3e.jpg)

**Comment by corrados** [comment]
The idea is to fix the bug that the new icon is not actually used for the Windows shortcut and also for the Mac version. The intention is not to change the icon design. I really like the new icon design and since the shape is modified, the new icon is also distinguishable from the normal icon for color blind people.

**Comment by marktheharp** [comment]
Cool - thank you.

**Comment by geheimerEichkater** [comment]
> @geheimerEichkater I need the Windows and Mac icon format for the new Jamulus server icon as well. Can you please create these?

Done, issued pull request. Files are named "jamulus-server-icon-2020" and .ico/.icns

Have a nice evening!

**Comment by corrados** [comment]
Great, thank you :-).
