### ISSUE TITLE
[Not a bug] Many thanks!

### ISSUE THREAD

**Issue by gegeweb** [corrados/jamulus#719]
Sorry for hopening an issue. ;)
No issues on my side at this time.

I just wanted to thank you and congratulate you for this great software!

Well documented, I have installed a server running on a Raspberry Pi4 behind a 1 Gb/s fiber recently. Works verry well.
And tonight I played on a Belgian server (I'm in France) with no latency and a good sound.

**Comment by ann0see** [comment]
That's really great to hear. Did you use the documentation from jamulus.io?

**Comment by gegeweb** [comment]
> That's really great to hear. Did you use the documentation from jamulus.io?

Yes, of course! ;) It is very well made and accurate.

This one : https://jamulus.io/wiki/Server-Rpi
And this one : https://jamulus.io/wiki/Server-Linux#running-a-headless-server

I've compiled the server on the Rpi4.

During yesterday afternoon's jam, we were five musicians, including a guitarist in Spain and a drummer at the Luxembourg border, the other three in France. The server runs near Paris in France behind a residential connection.
Everything worked well.
2 Mb/s on the server's interface at most of the use and very little CPU and memory resources used.

**Comment by ann0see** [comment]
Great. I don't know who wrote the RasPi instructions but I think you should thank this user. @gilgongo did a lot of work.

I still have a few questions: 
* How did you find out about Jamulus? 
* Do you know about the forum on SourceForge?
* Do you have Windows Users? If yes, do they use ASIO4All and how difficult was the setup?
* How high would you consider the hurdle to setup (especially windows)?
* How high would you consider you PC skills? I assume you are quite skilled since you know about Raspberry Pis

**Comment by gene96817** [comment]
Answers inline below.

Gene
--------------------------
Eugene Chang
gene96817@gmail.com
781-799-0233



************
What is the attached file signature.asc?
If you use PGP compatible mail software, this file holds a cryptographic digital signature to prove the email was really sent by me. As a bonus, if you are using PGP, our email could be cryptographically secure and private from anyone intercepting the email.










> On Nov 10, 2020, at 7:54 AM, ann0see <notifications@github.com> wrote:
> 
> 
> Great. I don't know who wrote the RasPi instructions but I think you should thank this user. @gilgongo <https://github.com/gilgongo> did a lot of work.
> 
> I still have a few questions:
> 
> How did you find out about Jamulus?
Internet search back in March
> Do you know about the forum on SourceForge?
Yes. I am still confused about the coordination between GitHub and SourceForge.

> Do you have Windows Users? If yes, do they use ASIO4All and how difficult was the setup?
Helping to onboard Windows users is awful. Many of them are clueless about what to do after installing ASIO4All.
They don’t know how to think about configuring their device(s).

> How high would you consider the hurdle to setup (especially windows)?
Awful. I wish I wasn’t the de facto support guy for my chorus. This is the largest issue that is keeping my chorus from using Jamulus, because the chorus won’t use it if all the members are not onboard.
> How high would you consider you PC skills? I assume you are quite skilled since you know about Raspberry Pis
My PC skills are rusty (I try not to be a PC expert and enjoy the convenience of my Mac). I am a theoretician on the RPi and Linux. I miss my Unix (LOL). Actually, I am struggling with finding documentation. I am fine if I just have documentation. I am really great solving the tricky problems once I have enough documenbtation.

**Comment by gilgongo** [comment]
Regarding Windows and device configuration - when you say people are clueless about what to do after installing ASIO4All, I take it this means they can at least work out how to install ASIO and launch Jamulus, but then don't know what to do once Jamulus starts? In which case @ann0see idea about having some kind of "First start" message on the main mixer screen would seem a good one (that is, a message that shows if they have yet to launch the Settings screen where the ASIO config button is). 

At least I take it that they are not seeing the "Jamulus needs ASIO to run" message which shows if they've not installed ASIO.

**Comment by gene96817** [comment]
Some of my observations could be dated with all the ongoing work. I am trying to stay focused on some near term tasks and not be an expert on many issue (just yet).

Since we tell new users know they need to install the ASIO driver, they usually manage to download the driver and install it. That is relatively easy. Most of the users don’t know much about drivers. Even if they are told to go to Settings and open (configure) the ASIO driver, they are bewildered with the concept of chipsets and dealing with builtin device, default devices, etc. Further, if the configuration changes when they plugin a headset or microphone, they don’t know how to think about that. Then there are the choices of using the built-in mic and plugged-in headset or, maybe, using the mic in the headset and not using the default speakers.

It is also confusing for these users to find an ASIO interface in Jamulus. Then they don’t know if the Jamulus interface supersedes the configuration through setting or if hey have to configure ASIO in both places. Does the order matter? Does it matter if some choices are contradictory? What choices are contradictory? These things might be relatively basic to us. It took me a long time to accept some users need hand-holding through all these steps.

Oops…. Handholding is not allowed, we have to be socially distanced. Further, we cannot use Zoom desktop sharing for support because Windows does not allow Jamulus and Zoom to simultaneously access the audio stream.

Also bad, some of our younger members don’t need help. They are fearless in diving in and twiddling with the settings. They seldom think they might be making a mistake. When it doesn’t work, the just blame the software for being stinky.

I have been away from Windows application development long enough that I no longer know know if it is possible to make Windows, Jamulus, and Zoom (or Jitsi) to be plug-n-play.

I do know to get a chorus on Jamulus, it is necessary to get every member onboard. That can be a challenge.

Gene
--------------------------
Eugene Chang
gene96817@gmail.com
781-799-0233



************
What is the attached file signature.asc?
If you use PGP compatible mail software, this file holds a cryptographic digital signature to prove the email was really sent by me. As a bonus, if you are using PGP, our email could be cryptographically secure and private from anyone intercepting the email.

**Comment by gilgongo** [comment]
Apart from giving people Raspberry Pis or handing out USB keys with Jamulus OS, the problems with Windows are currently pretty intractable since they are in the relationship between ASIO4ALL and Windows, and further dependent on (as you point out) various things local  to the user's setup, like mics and headsets. 

Some form of helper application designed to guide the user though the process of choosing devices has been suggested, but the degree to which that might help is hard to know. There is always the question of how other ASIO-dependent applications do it, but as far as I can see they have the same issues.

**Comment by gegeweb** [comment]
> Great. I don't know who wrote the RasPi instructions but I think you should thank this user. @gilgongo did a lot of work.

So thanks to @gilgongo 

If you want help to translate the documentations in french, I could help or do that, just tell me how-to…
 
> I still have a few questions:
> 
>     * How did you find out about Jamulus?

By searching on search engines with the keywords "jam", "jamming", "online".
And also on this site (in French) : https://www.bassetorius.fr/applications/jamulus/

>     * Do you know about the forum on SourceForge?

Yes, I've already read some posts following my research.
I should go there more often... ;)

>     * Do you have Windows Users? If yes, do they use ASIO4All and how difficult was the setup?

No Windows users around me.
Only MacOS or Linux users.
Maybe there were some among the musicians I played with.
Windows is not the best system for music! (and for anything else, but no troll! :D)
MacOS seems much more popular in the world of music.

>     * How high would you consider the hurdle to setup (especially windows)?

Under MacOS it is disconcertingly simple.
In my opinion, the main problem does not come from the software but from the need to be equipped with an audio interface (not everyone has one, for a drummer the setup becomes more complex), to have a good internet connection and to be able to connect to the router by wire.

However I did some tests with the client in WiFi on my network and server, it works well as long as I have a good WiFi reception.
And with a guitarist friend, in ADSL (7 Mb/s down, 1 Mb/s up) and the client in WiFi.
We managed to play together despite the latency on his side.

>     * How high would you consider you PC skills? I assume you are quite skilled since you know about Raspberry Pis

I administer FreeBSD servers, I know and use Linux since 1999 and MacOS since about 2005.
I do system administration under Windows since two years.
Let's say I'm a self-taught with a good level of knowledge and I'm comfortable with computers.

I prefer MacOS or Linux for the Desktop, FreeBSD for the servers. And if I can avoid Windows... I avoid it ;)

I plan to test a complete audio solution under Linux and Ardour in my home-studio soon. I have to find the right USB or Thunderbolt audio interface. My StudioLive AI in Firewire complicates the problem.

**Comment by gene96817** [comment]
> Apart from giving people Raspberry Pis or handing out USB keys with Jamulus OS, the problems with Windows are currently pretty intractable since they are in the relationship between ASIO4ALL and Windows, and further dependent on (as you point out) various things local to the user's setup, like mics and headsets.
> 
> Some form of helper application designed to guide the user though the process of choosing devices has been suggested, but the degree to which that might help is hard to know. There is always the question of how other ASIO-dependent applications do it, but as far as I can see they have the same issues.

I agree. My next few weeks will be to explore JamulusOS and understanding if this will make it easier for Windows users. I'd like to hear from anyone with experience giving JamulusOS to Windows users. I'd like to build on your experience.

**Comment by chrisrimple** [comment]
Not sure what progress has been made, but I thought someone had previously compiled Jamulus for Linux onto a bootable thumb drive.  Perhaps that could be given to singers that are Windows users, so they would only need wired ethernet + USB headset + thumb drive to get started.

**Comment by gilgongo** [comment]
The Achilles heel of Jamulus OS is getting it to remember the individual system's settings between reboots. I think it's possible to an extent but I've not tried properly.

**Comment by gene96817** [comment]
@gilgongo  Good point. To have persistence, we need a convention to save individual settings. My suggestion would be to save this as a file on the hardware's default disk. Consider updating the file whenever the settings are changed. Then it would be resistant to unexpected shutdowns. If anyone wants to go the extra distance, this file could have a small log for troubleshooting. The user only needs to email the file for help.

**Comment by chrisrimple** [comment]
If using a thumb drive, can't settings be saved there, as the bootable disk?  Ignore the computer's hd altogether - in concept, it wouldn't even need one.

**Comment by gilgongo** [comment]
Jamulus OS uses live USB, which allows you to have a partition on the USB key that stores stuff between reboots (not sure how you set that up though). Mind you, you can’t modify system files or install hardware drivers, so I don't know if that might affect a Jamulus setup. I think you would be able to upgrade Jamulus though and preserve the Jack settings, so maybe that would be enough.

**Comment by chrisrimple** [comment]
I assume that jamulus.ini also stores to the USB disk, which would be good.

**Comment by gene96817** [comment]
I would be reluctant to leave the USB disk connected for a long session. I feel that the USB disk sticks out in a vulnerable way, just waiting for an accident. It would be (physically) safer to boot up and then remove the USB disk.

**Comment by chrisrimple** [comment]
I think there's little to no risk to the USB disk.  Keep in mind that the primary audience for this solution is non-technical singers, without audio interfaces, who will also be using a USB adapter for ethernet and a USB or headphone jack headset.  They've already got USB ports in use during their Jamulus session, and aren't likely to be knocking into their USB disk.

**Comment by ann0see** [comment]
@gegeweb this issue goes a bit off topic now. Nevertheless: Thank you very much for your answers!

> By searching on search engines with the keywords "jam", "jamming", "online".

That's important to know. Actually I used similar search terms to find jamulus. In my opinion it should also be high if somebody searches for "online rehersal". We should have a look at seo, I think.

This should be discussed in the documentation repo: https://github.com/jamulussoftware/jamulussoftware.github.io

> No Windows users around me.
> Only MacOS or Linux users.

Yeah, that's much easier. I assume that Mac/Linux users have fewer problems than Windows but Windows is industry standard.
> I administer FreeBSD servers, I know and use Linux since 1999 and MacOS since about 2005.

Ok. So you are quite skilled (especially with audio software too if you have a home studio)

> If you want help to translate the documentations in french, I could help or do that, just tell me how-to…

Yeah, that would be great since we are missing a french translation. I don't speak french well enough to translate the documentation so you would be a great help. Have a look at the readme files in https://github.com/jamulussoftware/jamulussoftware.github.io I hope they explain everything. Just open an issue and a pr there.

**Comment by gegeweb** [comment]
> Sorry that this issue goes a bit off topic now. Nevertheless: Thank you very much for your answers!

Don't worry, the off-topic is interesting.
I've taken up learning the bass again and I'm also helping out a friend who is a guitar teacher. My friend is on MacOS, my teacher is on Windows (so I have Windows users around me!).
Because of the pandemic and the lockdown in France (and probably in other countries as well), courses now take place online by videoconference.
But the latency is horrible with video software and it is impossible for the student and the teacher to play together.
So using Jamulus in this context for the audio and the video software (Jitsi Meet in my case) for the image (muted sound) is an excellent solution.
I tested it with my friend guitarist. It's very useful.
However, the setup must be as simple as possible for students and teachers who do not necessarily have the technical skills in computers or audio equipment other than the computer's microphone and speakers and most certainly under Windows for the majority.

**Comment by gegeweb** [comment]
> Yeah, that would be great since we are missing a french translation. I don't speak french well enough to translate the documentation so you would be a great help. Have a look at the readme files in https://github.com/jamulussoftware/jamulussoftware.github.io I hope they explain everything. Just open an issue and a pr there.

Thank you.
I'll start working on it, when I have a doubt I use DeepL and correct the French translation if it's not quite right. I also use it to translate my French or check that my English is correct with the French translation.

It's a bit of work! ;)

**Comment by gegeweb** [comment]
> Great that we get a French translation. Can we now close this Issue?

Yes, you can close.
I'm working on the translation : https://github.com/jamulussoftware/jamuluswebsite/pull/41 
It's quite advanced! Thanks to lockdown and partial unemployment...
