### ISSUE TITLE
Clear All Stored Mute Settings

### ISSUE THREAD

**Issue by chrisrimple** [corrados/jamulus#731]
Can we please add an Edit > Clear All Stored Mute Settings menu item, similar to the existing Clear All Stored Solo Settings?  Or maybe change Clear All Stored Solo Settings to clear Mute as well, and rename the menu item to Clear All Stored Solo & Mute Settings?

**Comment by corrados** [comment]
Why to change all mute settings? If one user is muted, it does not hurt your ongoing session if such a new client enters the server. Things are different with the solo switch. If you set a user to solo and he leaves the server, his solo state is stored. When you are now in a session (e.g. even a live session on worldjam) and now that user enters in between a song, since he was set on solo, you won't hear your band members anymore but only that new user. Therefore it is important before a live session to un-solo all stored solo states. Therefore we introduced that setting. I do not see such a requirement for the mute state, actually.

**Comment by chrisrimple** [comment]
If the Mute state is also stored between sessions (and I assume that it is), then these situations can occur...

- I'm on a public server with other musicians.  For whatever reason, some of them mute me.  Let's call one of them John.
- Later, I'm running sound checks for the WorldJam, and John joins my soundcheck server.  He doesn't realize that he's got me muted, and can't hear me giving him instructions for soundcheck.

Or...

- I'm on a server with other singers.  The choral director tells everyone to mute the Bass singers, then one of the Bass singers (John) leaves the session early.
- At the next rehearsal, John is muted for all singers, and some don't realize it, and they can't hear him.

And so on.  By providing a Clear All Stores Mutes solution, users can be instructed to Clear All Stored Mutes before joining a WorldJam server, before joining a choral rehearsal, etc.

**Comment by corrados** [comment]
> Or maybe change Clear All Stored Solo Settings to clear Mute as well, and rename the menu item to Clear All Stored Solo & Mute Settings?

Ok, so let's go with that solution. That should be a simple change in the code. I'll schedule it after the next release.

**Comment by corrados** [comment]
It's implemented on Git now -> closed.
