### ISSUE TITLE
Suggestions for the UI in French

### ISSUE THREAD

**Issue by gegeweb** [corrados/jamulus#759]
@trebmuh 

I know (since we are working together on the translation of the doc) that you are attached to stay as close to English as possible.
But in some cases, literal translation is not the right approach (IMHO).

First, noticed some inconsistencies in the menus, I don't know if it's voluntary or not : 
<img width="429" alt="Capture d’écran 2020-12-04 à 06 45 51" src="https://user-images.githubusercontent.com/9108457/101127174-3ceb8c80-35fd-11eb-9817-2bae311b0f27.png">

There is « trier les utilisateurs du canal » or « trier les utilisateurs des canaux ».
As an end user I find it hard to understand, it's not very clear and strange wording.

I would have translated as follows:
* trier les canaux par nom de musicien _or "utilisateur"_
* trier les canaux par instruments
* trier les canaux par groupe
* trier les canaux par ville du musicien _or "utilisateur"_

Second,
for « régler tous les _chariots_ sur le niveau d'un nouveau client », « chariot », even if that could be a translation for "fader", in this context, a mixing desk, "potentiomètre" should be better (Exactly: "potentiomètre rectiligne", but we use only "potentiomètre", or "tranche" for "tranche de console" (slice of mixing desk) when we talk about of all the elements of a channel (gain, selector, fader, pan…).

And for the about message, why not use the slogan. « bœuf » doesn't make sense for everybody.

"Cette app" -> "Ce logiciel" or "Cette application", "permet aux musiciens de jouer ou improviser en temps réel sur Internet" (with a *I* uppercase for "Internet").

**Comment by gegeweb** [comment]
> I would have translated as follows:
> 
> * trier les canaux par nom de musicien _or "utilisateur"_
> * trier les canaux par instruments
> * trier les canaux par groupe
> * trier les canaux par ville du musicien _or "utilisateur"_

After taking a look at the UI in english, I think these wordings should be more close to the original meaning
* trier les canaux utilisateur par nom
* trier les canaux utilisateur par instrument
* trier les canaux utilisateur par groupe
* trier les canaux utilisateur par ville

("canaux" only or "utilisateurs" only should be used. It's enough to understand, shorter and more usual.)

That is how I understand the UI in English, and that's what it does.

**Comment by trebmuh** [comment]
> There is « trier les utilisateurs du canal » or « trier les utilisateurs des canaux ».

Well see. I didn't pay attention that there was "_du canal_" and "_des canaux_". They're all now "du canal".

About changing it, I decided against using "_trier les canaux utilisateur par_" because that's not what's written in English.
In English, the text is "_Sort Channel Users by XXXX_", and not "_Sort user channels by XXXX_". If you think that's a mistake against what they does really, then you should report that against the original English wording.

> for « régler tous les chariots sur le niveau d'un nouveau client », « chariot », even if that could be a translation for "fader", in this context, a mixing desk, "potentiomètre" should be better (Exactly: "potentiomètre rectiligne", but we use only "potentiomètre", or "tranche" for "tranche de console" (slice of mixing desk) when we talk about of all the elements of a channel (gain, selector, fader, pan…).

About "_fader_" translation.

I'm not a huge fan of "_potentiomètre_" or "_potentiomètre rectiligne_" since they are more of an electronic definition and, as a consequence, a too much corporate wording while Jamulus is made for being used by pretty much anyone. Moreover, "_Potentiomètre_" alone is usually hitting a "_rotary potentiometer_" picture in people's mind and "_potentiomètre rectiligne" is a too long word for me while I was searching for something which should translated in one word only.

There is also "_atténuateur_" which sounds correct to me and is very used (see [https://fr.audiofanzine.com/glossaire/a.play,word.Att%C3%A9nuateur.html](the audiofanzine glossary) and [https://fr.wiktionary.org/wiki/att%C3%A9nuateur](the French witionnary) as examples).

Finally it seemed to me that "_chariot_" was probably likely to visually and functionally be a word understandable by pretty much anyone, and had the advantage of being a short word.

So for now, I do prefer to keep it as it is and if I needed to change, I'd probably go for "_atténuateur_" rather than "_potentiomètre_"


> And for the about message, why not use the slogan. « bœuf » doesn't make sense for everybody.

I disagree here. Bœuf is more understandable for most people in comparison with "jam" which is an anglicism. See [https://fr.pons.com/traduction/français-anglais/have+a+jam+session](here), [https://dictionnaire.reverso.net/anglais-francais/jam+session](there) as examples.

> "Cette app" -> "Ce logiciel" or "Cette application", "permet aux musiciens de jouer ou improviser en temps réel sur Internet"

The English wording here isn't the "This application" or "This software", but "This app". So, I sticked to it and i don't see a (good) reason to change it. If you think that the English wording is wrong, please ask again the English version.


> (with a I uppercase for "Internet").

1. the English wording is without a capital letter
2. the official consensus in French tends to prefer the use without capitals because as a common name

**Comment by gegeweb** [comment]
> So for now, I do prefer to keep it as it is. If I needed to change, I'd probably go for "_atténuateur_" rather than "_potentiomètre_".

In this case, why not "tirette"? (https://www.larousse.fr/dictionnaires/francais/tirette/78194)
On my side sounds better than "chariot".

**Comment by trebmuh** [comment]
"tirette" in a musical context is usually used as a translation for the Hammond organ drawbars.

**Comment by gegeweb** [comment]
> About changing it, I decided against using "_trier les canaux utilisateur par_" because that's not what's written in English.
> In English, the text is "_Sort Channel Users by XXXX_", and not "_Sort user channels by XXXX_". If you think that's a mistake against what they really do, then you should report that against the original English wording.

I think, but perhaps no, is the english UI a translation from another language? /ping @corrados 
In any case "Trier les utilisateurs du canal" doesn't make sense to me, I really don't understand what it can mean!
And when I read the english I understand "Sort user channels".

**Comment by gegeweb** [comment]
> "tirette" in a musical context is usually used as a translation for the Hammond organ drawbars.

Yes but the user see a mixing console, not an organ. ;) 

That was just a suggestion, because "chariot" sounds very strange to me.

**Comment by trebmuh** [comment]
> In any case "Trier les utilisateurs du canal" doesn't make sense to me, I really don't understand what it can mean!
> And when I read the english I understand "Sort user channels".

But you're wrong here. It isn't "Sort user channel**s**" but "Sort channel user**s**". 
* Sort user channels = Trier les canaux-utilisateur
* Sort channel users = Trier les utilisateurs du canal


From the proposition you made above, it looks like you're making a confusion with what the "channel" word is referring to here. As far as it's written in the English version, "channel" is not referring to "one strip by user", but to the server we are connecting to. We are connecting to this server (called "channel" here), and using the "Sort channel users by name" is sorting the users strips in this "channel" by their alphabetical name.

@corrados maybe we could change the English wording for "Sort channel users by XXXX" by only "Sort users by XXXX" and so on? It could help to disambiguate here.


>> "tirette" in a musical context is usually used as a translation for the Hammond organ drawbars.
> 
> Yes but the user see a mixing console, not an organ. ;)

Still it could be confusing and, as far as I'm concerned, I never saw a translation for "fader" using this word

> That was just a suggestion, because "chariot" sounds very strange to me.

I know it can be strange-ish. Bear in mind that this is a trade-off because there is AFAIK nothing fitting better (understandable by a lot of people, and being a shorty one word) without the need of adding an explanation or an adjective.

**Comment by corrados** [comment]
> maybe we could change the English wording for "Sort channel users by XXXX" by only "Sort users by XXXX"? It could help to disambiguate here.

I think we need a native english speaker. Anyone here who can help us with this?

**Comment by gegeweb** [comment]
> From the proposition you made above, it looks like you're making a confusion with what the "channel" word is referring to here.

That's it.

**Comment by gegeweb** [comment]
>  "Trier les utilisateurs du canal"

We agree that this means nothing in context?
And that it doesn't fit with the action that follows.

@corrados the English is a German translation?

**Comment by gegeweb** [comment]
> Still it could be confusing and, as far as I'm concerned, I never saw a translation for "fader" using the "tirette" word.

https://fr.wikipedia.org/wiki/Console_de_mixage : 
« _le plus souvent avec potentiomètres rectilignes (tirettes, faders) et potentiomètre d'affectation gauche/droite (panoramique pan)_ »

**Comment by trebmuh** [comment]
> The english is wrong… I think.

Not really. I've explain you above why.

> We agree that this means nothing in context?

No. It means something. But this can probably be improved.

@corrados : this is my understanding that you're the one doing the German GUI translation. The German translation is [Sortiere die Kanäle nach dem Namen](https://github.com/corrados/jamulus/blob/master/src/res/translation/translation_de_DE.ts#L988) and hence, is translating into English by "_Sort the channels by name_" (according to Deepl, and my college German 2 years). If so, there is no mention of "users" here.

@corrados moreover, I'd like to make sure that we all understand what you are referring with "Kanäle" ("channel" in English). Are you referring here to "a canal is a user strip" and then, " one channel" = "one user"? or anything else as I first thought?

**Comment by corrados** [comment]
> the English is a German translation?

Yes since German is my native language.

> If so, there is no mention of "users" here.

Yes, you are right.

> Are you referring here to "a canal is a user strip"

What gets sorted is the bundle of fader/pan/mute/solo/label. This bundle I call "channel". Maybe there is a better word for it. At least in German language "Kanal" describes the correct thing on a mixer board.

**Comment by gegeweb** [comment]
> What gets sorted is the bundle of fader/pan/mute/solo/label. This bundle I call "channel". Maybe there is a better word for it. At least in German language "Kanal" describes the correct thing on a mixer board.

That's how I understand it.

In French, "canal" or "tranche" is used by sound technicians (so channel is good, it is used to describe this in english on mixing desk manual).

The right english translation could be :

* sort channels by Name 
* sort channels by Instrument
* sort channels by Group
* sort channels by City

**Comment by trebmuh** [comment]
A correct English translation could be that. Agreed.
Moreover, it's shorter so doesn't use too much space and is less confusing.

That said, while it's correct that technically, it's representing the "stripes/channels" from software purpose, what the software representing here is the person represented by a "stripe/channel".

I'd then propose to use:
* sort users by Name
* sort users by Instrument
* sort users by Group
* sort users by City

or:
* sort musicians by Name
* sort musicians by Instrument
* sort musicians by Group
* sort musicians by City

Thoughts?

**Comment by gegeweb** [comment]
> I'd then propose to use:
> 
>     * sort users by Name
> 
>     * sort users by Instrument
> 
>     * sort users by Group
> 
>     * sort users by City
> 
> 
> or:
> 
>     * sort musicians by Name
> 
>     * sort musicians by Instrument
> 
>     * sort musicians by Group
> 
>     * sort musicians by City
> 
> 
> Thoughts?

IMHO, if the original intention is to describe and talk about elements of a mixing desk, channel should be used.

But I'm not the author of the software. So that's just my opinion.

**Comment by corrados** [comment]
@gilgongo Can you please comment?

**Comment by gilgongo** [comment]
Yes, we've not been very consistent in how we refer to the things that are shown in the UI connecting to the server. "Users",  "Channels" and I think we may also refer to them as "Sliders", "Clients" and also "Players" and "Musicians" somewhere. 

As to what's best, it may depend on whether people think of a "Channel" as being separate from the human connected to it. This is one of the many places where Jamulus diverges from a real world mixing desk because in the real world, you can have a channel with nobody connected to it. I think this was something some people may have found difficult about "Mute Myself" for example. So if we choose a "human" term ("Users", "Players" or "Musicians") and abolish the concept of a "Channel" then it may be good because a "human" word is closer to the reality of the situation. For each "thing" on the screen there is a human at the other end. So it's more explanatory than a "system" term like "Channel".

There is of course a very small edge case in which the same person may be connecting two or more clients. And singers aren't "players" (or even "musicians") in English, so there is that too along with the idea that you don't sort people you sort their attributes. But maybe that's too detailed :-)

On the other hand, if we choose a "system" word like "Channel", "Client" or "Slider" then it may be more consistent with the visual metaphor, but if we invite people to think of Jamulus as a mixing desk, and use the vocabulary from that, you can't blame them for taking the analogy too far and then getting confused. 

Hm. I feel that a "human" term like "Player" may be best as it's closer to what Jamulus is doing, but it's a tough call.

**Comment by gegeweb** [comment]
@gilgongo recently I've explained "how to see Jamulus", the software (client) and the server (public or private) to somebody connected to my server wich looked some help :

_First, think of the public server as an open rehearsal studio, where musicians are already there.
Enter discreetly (Mute Myself), listen, and see if you can join the band. If it is a private rehearsal just listen or look at an other open studio (public server) where they are jamming.
Second, think of the client as your amp, your microphone, for what you send to others, and the mixing console as your personal monitor mix. And on server side the main monitor mixing desk that you control with your client.
If the server is private, so you should have the key (address) to enter, and you will not be disturbed by others._

Of course, I'm a musician and sound technician, so for me to see a mixing console and use the terms that describe its components is natural, I undestand "channel" for what it is in the context. (It's also why I doesn't see the wrong wording in the EN GUI, I "translated" automatically, and why the French GUI sound strange for me)
And it's also natural for me to see the client recording and/or broadcasting as the stage and the musician's clients as the personal monitoring circuits.

**Comment by gilgongo** [comment]
OK. But is there anything wrong with referring to "Player"? 

In the study of UI design, it's well known that if you decide to use an analogy, then you will have limited control over users' understanding of your UI. This is because your UI is ultimately not the thing you are taking the analogy from and will probably in some way diverge from it. This is why I tend to favour us referring to "Players" (or other "human" word) because the understanding of that word is not tied to an analogy.  We are therefore less likely to lose control of its meaning.

**Comment by gegeweb** [comment]
> OK. But is there anything wrong with referring to "Player"?

Not for me.;)

**Comment by trebmuh** [comment]
@gilgongo I'm under the impression that if we're to go for "users", then it would embrace "instrument player", "singer", and even "listener", which means that all the potential roles would be covered. And would still be a "human" description.

**Comment by gilgongo** [comment]
Yes, "User" would be generic enough in that regard. It's just a pity it can't be more musical :-)

BTW I'm looking at the docs to get a sense of the effect of standardising on the word "User". I think it might clarify things in other contexts too perhaps. For example, in [this passage](https://jamulus.io/wiki/Software-Manual) where we are currently using "Channel" in two ways, "User" would give "Channel" a distinct (and clearer) meaning:

The current wording:

> The VU meter shows the input level at the server - that is, the sound being sent.
>
>If you have set your Audio Channel to Stereo or Stereo Out in your Settings, you will also see a pan control (shift-click to reset).
>
>If you see a “mute” icon above a channel, it means that musician cannot hear you. Either they have muted you, soloed one or more channels not including yours, or have set your fader in their mix to zero.

With "user" instead of "channel"

> The VU meter shows the input level at the server - that is, the sound being sent.
> 
> If you have set your Audio Channel to Stereo or Stereo Out in your Settings, you will also see a pan control (shift-click to reset).
>
>If you see a “mute” icon above a user, it means that musician [person?] cannot hear you. Either they have muted you, soloed one or more users not including yours, or have set your fader in their mix to zero.

So perhaps this would be another reason to favour the use of "User" and not "Channel" (or "Slider" which should be reserved for the actual UI control for volume, or "Client" which is probably too geeky for non-technical people).

**Comment by corrados** [comment]
Ok, so I'll change the text now to:

* sort users by Name

* sort users by Instrument

* sort users by Group

* sort users by City


> If you see a “mute” icon above a user, it means that musician [person?] cannot hear you. Either they have muted you, soloed one or more users not including yours, or have set your fader in their mix to zero.

Ok, I can change this as well. Should we use "person" then?

**Comment by corrados** [comment]
BTW: Should it be
- No User**s** Sorting

or
- No User Sorting

**Comment by gilgongo** [comment]
"No User Sorting" 

BTW in the docs I could try to explain what the order would be in that case - something like "Users will be shown in order of their arrival on the server, until somebody disconnects, whereupon the next user will be shown in the previous user's position"?

**Comment by drummer1154** [comment]
> If you see a “mute” icon above a user, it means that musician [person?] cannot hear you. Either ...

Why not simply
"If you see a “mute” icon above a user then this user cannot hear you. Either ... "

>  "Users will be shown in order of their arrival on the server, until somebody disconnects, whereupon the next user will be shown in the previous user's position"

I think
"Users will be shown in the order of their arrival on the server. If somebody disconnects, this user is removed from the list."
should be clear enough.

**Comment by gilgongo** [comment]
@drummer1154 Yes, sorry - I didn't mean we'd literally say "musician [person?]" :-) I meant:

"If you see a “mute” icon above a user then this person cannot hear you."

(The reason I say "person" and don't repeat "user" here is from a general documentation technique of always using a synonym if possible in order to avoid the possibility that the first term ("user") might not be understood.)

> "Users will be shown in the order of their arrival on the server. If somebody disconnects, this user is removed from the list."

Well yes, but it's the order we're talking about here, not the behaviour :-)

**Comment by corrados** [comment]
> My understanding is that that subsequent arrivals are put in the "slot" that the previous person took. But I'll leave that to @corrados to confirm.

That behaviour has actually changed in recent versions. If no sorting is enabled, a new user always is added to the right and does not appear somewhere in the middle between existing channels, see https://github.com/corrados/jamulus/issues/673.

**Comment by gilgongo** [comment]
> That behaviour has actually changed in recent versions.

OK good, so I'll update the docs to say that and start standardising on "User" instead of "Channel".

**Comment by corrados** [comment]
Are these things fixed now? Can this issue then be closed?

**Comment by trebmuh** [comment]
@corrados : yes.
