### ISSUE TITLE
Jamulus alternatives

### ISSUE THREAD

**Issue by corrados** [corrados/jamulus#763]
Despite the fact that the community performing online jam sessions and rehearsals has grown significantly during the pandemic, it is still a very small community compared to the number of musicians in the world. So, I definitely do not see Jamulus alternatives as an enemy but as a help to grow the online jamming community. It's similar to, e.g., virtual reality. Compared to the number of gamers in the world, just very few actively using virtual reality. To spread the information that this is a great technology, it requires multiple alternatives.

So, I want to use this Issue just as a source of information. **Please do not use this Issue to talk bad about any software mentioned here!** I am sure, all of the alterntives do their job well and as usual, every software has its pro and cons. We should focus on a technical discussion, e.g. what are the strengths of each solution.

I start with a list of software I know (and actually this list has grown lately):

- [JamKazam](https://jamkazam.com)
  - commercial software
  - peer-to-peer concept
  - has a lot of features (jamtracks, social features, great audio quality, etc.)
  - offers a special hardware "Jamblaster"

- [SoundJack](https://www.soundjack.eu)
  - closed source software but free of charge
  - peer-to-peer and client-server (client-server was added recently)
  - exists for a very long time, driven by a professor, had received some fundings

- [JackTrip](https://ccrma.stanford.edu/software/jacktrip)
  - uncompressed audio
  - sophisticated algorithms to, e.g., adjust sampling rates, etc.
  - recently a [foundation ](https://www.jacktrip.org) has been created

- [SonoBus](https://sonobus.net)
  - open source, peer-to-peer

- [HPSJam](https://github.com/hselasky/hpsjam)
  - open source, client-server concept (very similar to Jamulus)
  - uncompressed audio for better audio quality
  - just recently created, still in an early stage

- Software which is not maintined anymore or in process of restarting the service:
  - [eJAMMING AUDiiO](http://www.ejamming.com)
  - [sofasession](https://www.facebook.com/Sofasession/posts/2901428133250846)

**Comment by ann0see** [comment]
Actually I chose and found Jamulus because of the client server principle (since that makes the software much easier to Setup compared to e.g. JamKazam). The only problems I der at the Moment are

1. Jamulus is unsigned (especially the Windows defender SmartScreen warning doesn't make Jamulus look trustworthy)

2. ASIO4All is sometimes difficult to setup

3. There's no real working Android or iOS client (none of the others support mobile devices yet)

4. You can't use WiFi

**Comment by drummer1154** [comment]
@corrados 

I think it is a very good idea to provide a comparison beween SW packages. I would kindly ask you to add
- Jamulus
- list of supported OSs
- consistent information regarding the principle
- maybe a list of known problems (as e.g. the "unsigned SW" issue in Jamulus and its difficulty to be set up "correctly")

of course only as far as you know - maybe put a question mark where you don't.

Many thanks
Helmuth

**Comment by chrisrimple** [comment]
My [Remote Band Rehearsals](https://docs.google.com/document/d/1smcvsxdaaViPQvGMQHmah_6BQeqowhmGSFMHfnlY2FI/) doc breaks down Real Time apps and Delayed Sync apps, and includes information on:

Real Time apps
- Jamulus
- JamKazam
- SoundJack
- JackTrip

Delayed Sync apps
- Ninjam / Ninbot
- Jamtaba
- Jammr.net

**Comment by gilgongo** [comment]
As an aside, Jamulus is listed on [Wikipedia](https://en.wikipedia.org/wiki/List_of_music_software#Internet,_RSS,_broadcast_music_software) under "Internet, RSS, broadcast music software" but none of others are mentioned. I'll add them.

**Comment by gene96817** [comment]
Knowing about the alternatives and their strengths is very important. There may be good ideas to adopt.
It is also good to know about the weaknesses of each solution. There is always a balance between strengths and limitations.

I started out with JamKazam because I wanted to avoid managing a server. The scaling issues in a peer-to-peer architecture quickly made it clear supporting a (larger) group of musicians (with mixed technical skills) was a lot easier with Jamulus.

**Comment by drummer1154** [comment]
@gene96817: Same for our trio, and as JamKazam now wants money, they are out of our list (btw their GUI is absolutely ugly from my PoV).

@chrisrimple: I have downloaded a PDF version of your document lately. Many thanks for this huge compilation and the insight.

Within this issue here I recommend to keep the list more simple and - as Volker has already said - concentrate only on the technical aspects, which however could be augmented a bit, see https://github.com/corrados/jamulus/issues/763#issuecomment-739243535 above. I hope this is not asking too much as Volker needs to edit his comment to incorporate our input, else the information will become inconsistent.

Cheers
Helmuth

**Comment by gene96817** [comment]
An interesting method to minimize our work to understand the alternatives is to invite those groups to provide/suggest the information we are seeking for our table. It is in their interest to have our table be correct. Do this early in the process, then we can verify the information.

**Comment by drummer1154** [comment]
Do you really believe they are willing to provide insight to a competitor (if an open source SW can be called a competitor)? The idea itself is very good, but in the first place we should write down our view and if they want to correct us they can input comments.

"Table" is a good buzzword: I think as of now we do not have a "table" but (only) a loose list ...
Maybe Volker can transform the list to a table - if it is not asking too much...

**Comment by gene96817** [comment]
@drummer1154  It is my experience that if we present ourselves in a collegial way and ask for help to ensure our table entries are correct, they will have two choices. They can provide information to ensure the data is correct or they can let us make our best guess (which might incorrectly identify a weakness). Our goal is to understand the strengths and weaknesses of each solution. Everyone knows there are no perfect solutions. Give each development team an opportunity to collaborate.

**Comment by drummer1154** [comment]
100% agreed, but the table is not yet there...

**Comment by chrisrimple** [comment]
Rather than capturing all the "competitor" information to the Issues list, perhaps it should be added to the Wiki?

**Comment by corrados** [comment]
I would even go a step further: Why not creating a comparison page in the Wikipedia?

**Comment by gilgongo** [comment]
I was going to suggest that since it's neutral ground and we might get more help doing it.

**Comment by drummer1154** [comment]
Sounds good for me. The only thing I hate about tables in Wikipedia is that it is not possible to keep the top row (header) visible when scrolling down. We should, however, avoid being flagged as "This article has multiple issues.".

**Comment by gilgongo** [comment]
OK, although we should probably first establish a simple the page without an actual comparison table, and write a preamble for it with a simple list. This is because there will probably be attempts to delete it early on (as spam, promotion, etc.) which we may have to fight in AFD. It also doesn't help that most of the other software doesn't have pages on Wikipedia either so we will look a bit spammy with external links.

But we'll see. I can try creating the page with the content we have and write a preamble. BTW I've put a COI notice on the Jamulus page which should help reassure deletionists :-)

**Comment by drummer1154** [comment]
Anyway I propose to create a table within this Issue and have the contents agreed prior to going more public.

**Comment by corrados** [comment]
Sure, you can create a table if you like. I'll then copy it to my initial post.

**Comment by drummer1154** [comment]
OK, I will create an Excel sheet using the info from this Issue and the format given in Wikipedia. Will take some days, though.

**Comment by hselasky** [comment]
Some points for **HPSJam** which is now v1.0.8:

- tries to be accessible to blind users
- cross platform as Jamulus is
- has solid redundancy in the protocol. Can suffer up to 30% packets loss before affecting the audio quality by using a simple XOR algorithm. And still does not send all packets twice!
- in the works (no social platform yet, server list, and so on)
- focuses on moving computational complexity to the client side, to allow a high number of connections.

This page is very useful comparing pros and cons between the different platforms available.

**Comment by gilgongo** [comment]
Just a bump on this: if we are to create a table, what would the columns be?

1. Licence
1. Architecture (p2p. c/s etc.)
1. Platforms (Web, Win, Mac, etc.)
1. Public/Private (Public only, Private only, Both)?
1. Synchronisation (Yes, No, Other)?

There's quite a bit that doesn't fit into the above, so maybe footnotes on an "Other features" column for now?

**Comment by gene96817** [comment]
How about:
6. recommended (typical?) and maximum number of participants
7.  video support
8. Date of first release
9 .Most recent release

**Comment by gilgongo** [comment]
OK so if people want they can add to this (apologies) Google sheet first, then we can put the markdown version on Wikipedia once it's reasonable. And carry on from there.

https://docs.google.com/spreadsheets/d/1pBC-c3RJ_agtkHq-ay2qEVTfHjulZQ2Q7N0czN8osVs/edit#gid=0

**Comment by drummer1154** [comment]
@gilgongo Thanks for creating the table already - noticed just now.
Can you please tell me the meaning of "Public/Private" and "Synchronization", thx.

**Comment by ann0see** [comment]
@gilgongo I wouldn’t say something like ”great audio quality“. In my opinion that’s too subjective

**Comment by gilgongo** [comment]
Public = anyone can come and play. Private = only you and your mates.

Synchronization = whether there is some some method in the system that is used to keep people in time. So delayed sync or maybe some metronome system like Endless uses.

**Comment by gene96817** [comment]
audio quality: to keep it objective, we should refer to the codec used.

Public/Private: would it be better to say open sessions vs closed sessions.

**Comment by drummer1154** [comment]
No audio quality column yet; I  think the codec alone is not enough, the audio bitrate is also an important parameter. An I also think we should add the sample rate.
Changed to Open/Closed Session.
I put question marks in cells where I am unable to find the required info in an acceptable timeframe.

**Comment by drummer1154** [comment]
@hselasky 
Please do me the favor to review/add the information in row 7 of the spreadsheet mentioned above, thanks.

Would you mind adding something like "One-man show, short release cycles" into column N? Just my impression, but you know better :-)

**Comment by gilgongo** [comment]
BTW what should we name the page? Does "Comparison of Remote Music Performance Software" work? 

My earlier thought of "Comparison of Internet Music Software" seemed to generic, like it would include iTunes. I thought about "Music Collaboration Software" too that also seems too wide like it might include Dropbox.

**Comment by gene96817** [comment]
one/two man shows
The first release and the most recent release will tell most of the story.

**Comment by gilgongo** [comment]
Now that we have a decent amount of data in [the table](https://docs.google.com/spreadsheets/d/1pBC-c3RJ_agtkHq-ay2qEVTfHjulZQ2Q7N0czN8osVs/edit#gid=0), I'll see if I can create the (English at first) Wikipedia page on Sunday (20th). 

Be aware that there **may** be an attempt to delete it because Wikipedia is like that. If it **does** go into "articles for deletion" (AFD) then we will need contest the deletion by consensus vote. It helps if anyone directly involved in any of the projects puts a "conflict of interest" (COI) declaration on their profiles for that reason, but I can help people with that if needed later.

**Comment by drummer1154** [comment]
@gilgongo From my PoV it is a bit premature - wouldn't it be better to eliminate as many question marks as possible prior to going to Wikipedia?

> I've added codec and bitrate

For **Jamulus** I just entered Opus, I didn't care for bitrate(s) as for our sessions audio quality was not an issue, and I do not know enough about them or where to look them up - (some) other platforms specify bitrates...

I explicitly asked for a **sample rate** column; this may be a crucial point for new users when choosing their suitable platform. E.g. my vDrum controller only operates at 44.1 kHz and is clock master for S/PDIF. So to work with Jamulus I needed a HW sample rate converter (my Lexicon Omega provides this function if initialized correctly by the application, but still it is extremely difficult and error prone to achieve the correct settings in both the iMac and in Jamulus).

So what do you think?

Regarding row 7 (HPS Jam, we had a typo in A7, corrected): I think most of the info was entered by @hselasky himself (most likely after my coment https://github.com/corrados/jamulus/issues/763#issuecomment-745615542, and I kindly ask him to clarify
- Built-in Sync: What does "Automatic" mean? The topic is about synchronization between the musicians in a session, maybe we need to point this out better somehow in the header (?).
- Misc. Notes: "accessible friendly" - "handicapped-accessible "?

**Comment by gene96817** [comment]
I am very glad to see this table emerging. I suggest in Column H - refrain from any "planned" features and in Column O - delete the adjective "sophisticated"

**Comment by gilgongo** [comment]
@drummer1154 

> wouldn't it be better to eliminate as many question marks as possible prior to going to Wikipedia?

You have until 00:00 GMT on Monday :-)  But joking aside, I think if we are to put it on Wikipedia we should do it soon so that we can deal with any deletion or modification efforts. I'm not familiar with the attitude to lists, for example, and we may be accused of [original research](https://en.wikipedia.org/wiki/Wikipedia:No_original_research). So, get it up to test it and see what the community thinks. With luck it will be fine. And incompleteness is not a problem for Wikipedia pages.

**Comment by hselasky** [comment]
Built-in Sync: What does "Automatic" mean? The topic is about synchronization between the musicians in a session, maybe we need to point this out better somehow in the header (?).

Automatic means that the packet rate is adjusted according to the input audio rate for both server and client.
Also excess audio is shrinked.

**Comment by gilgongo** [comment]
@hselasky  I expect we'll need to use footnotes fairly extensively in the table for this kind of thing :-)

**Comment by bflamig** [comment]
I just started playing around with Sonobus. (I like it so far -- I frankly like the interface better than Jamulus, -- so far. It's very techy to be sure). But I've only used it for like 10 minutes, so I'm sure my opinion will change :) Making connections was a piece of cake. You don't even have to know anything about IP addresses, as far as I can tell.

As far as the spreadsheet goes:

1) Sonobus runs just fine in Linux (in the spreadsheet it has showing as "[Linux]" rather than "Linux". I presume that means whoever made that entry hadn't tried it in Linux yet. I can say I installed it on a Raspberry Pi very easily.

2) Sonobus just came out with a new release, and it has a version number of 1.2.0. So that part of the spreadsheet could be changed.  I don't know what the initial release was. It appears that Sonobus is very new.

**Comment by gilgongo** [comment]
Feel free to edit the sheet with any findings you have - it's world r/w

**Comment by drummer1154** [comment]
I have put [Linux] in brackets because from their website I took the information that it is required to compile the SW by yourself. This is most likely not a problem for an experienced Linux user - but other platforms offer binaries.

Sorry to be imperfect here - I do not have any up-to-date ***X experience (Windows expert and forced Mac user :-).

Spreadsheet updated according to https://github.com/essej/sonobus - but I am not the owner, see above - and I think I need to step aside now because this research takes too much time for me and I'd rather like to invest in Jamulus improvement.

**Comment by gene96817** [comment]
It is best not to be too strict about details. Don't feel obligated to research the missing data for the other solutions. The information for the cells should be basic documentation for each solution. The table is really a "high level" survey of alternatives. The current content is already very informative for most readers. Let "experts" of the other solutions contribute content or corrections.

**Comment by bflamig** [comment]
> Feel free to edit the sheet with any findings you have - it's world r/w

I didn't know that. Thanks.

**Comment by bflamig** [comment]
> It is best not to be too strict about details. Don't feel obligated to research the missing data for the other solutions. The information for the cells should be basic documentation for each solution. The table is really a "high level" survey of alternatives. The current content is already very informative for most readers. Let "experts" of the other solutions contribute content or corrections.

For Linux, isn't it true that you have to compile Jamulus yourself as well? That's what I was getting it. It's not a big deal, just something I noticed on the spreadsheet.

**Comment by gilgongo** [comment]
OK I'll see if I can put the table on Wikipedia later today. I'd had a read of some of the guidance on lists and comparisons and I think we should be OK but we'll see.

**Comment by gilgongo** [comment]
OK it's live:

https://en.wikipedia.org/wiki/Comparison_of_Remote_Music_Performance_Software

And within about 10mins of me posting it. It's been flagged for improvement (for references, and more worryingly notability, but I think we can avoid that).

So - feel free (obviously) to edit, but try if you can to add references that are not primary (so ideally something like a recognised site writing about JamKazam and mentioning some of the features we list, for example).

**Comment by drummer1154** [comment]
@gilgongo Many thanks for this. I do not have a Wikipedia account (yet) and I am wondering if it would be a good idea to create one as drummer1154 (which I also use in quite some other places) - any advice? Maybe mailto dr.........@arcor.de ...

**Comment by gilgongo** [comment]
@drummer1154 Yes (assuming that ID is available). Having the same ID as you use here will be best. Be aware that newly created Wikipedia account attract suspicion if they start editing immediately, so if you do make any edits, best to add yourself to the disclosure notice on the Talk page beforehand. 

Also BTW I think we should leave it to settle for a few days to make sure all is well, maybe suggesting edits on the Talk page instead for example, before putting much more effort into it.

**Comment by chrisrimple** [comment]
I haven't been following this thread closely but understand that the goal is to publish a new (or update an existing) Wikipedia page.  I have a Wikipedia account and have been contributing small edits for years.  Same name as my account here.  Happy to help post to Wikipedia if needed.

**Comment by gilgongo** [comment]
@chrisrimple OK good. And account in good standing it nice to have. [The page](https://en.wikipedia.org/wiki/Comparison_of_Remote_Music_Performance_Software) has only just been created and has already been slapped for lacking citations and notability. I'd posted on the Talk page about that so if you can contribute that would be good.

**Comment by ann0see** [comment]
The site looks good. Doesn't Jamulus support up to 150 musicians?

**Comment by chrisrimple** [comment]
@gilgongo I've done some editing on [the Comparison of Remote Music Performance Software page](https://en.wikipedia.org/wiki/Comparison_of_Remote_Music_Performance_Software) and the Talk associated with that page.  The warning about citations and notability is automatic - I don't believe that was manually applied by a Wikipedia editor.  Technically, [we can remove it ourselves](https://en.wikipedia.org/wiki/Help:Maintenance_template_removal), although I think we should continue to expand the page content a bit more before doing so.  I'm going to try to find time in the next week or so to bring details from my [Remote Band Rehearsals doc](https://docs.google.com/document/d/1smcvsxdaaViPQvGMQHmah_6BQeqowhmGSFMHfnlY2FI/edit#) into the Wikipedia page, and also the [Networked Music Performance](https://en.wikipedia.org/wiki/Networked_music_performance) page.

**Comment by gilgongo** [comment]
Thanks - the flag was added by the user Spiderone (you can see from the history). Their profile looks like they might oppose removing the flag, so we should leave it there for a while I think. I've tried to add a couple of secondary sources.

**Comment by drummer1154** [comment]
@gilgongo / @chrisrimple How can I

> add yourself to the disclosure notice on the Talk page

Where to start from for this? My own page or the page with our table?

**Comment by gilgongo** [comment]
@drummer1154 You only need to declare COI if you are making edits to the page. In which case edit the Talk page and the flag at the top. Otherwise best to suggest edits on the Talk page. And yes, we could change the wording (also BTW I think I screwed up the table heading footnotes as they don't link properly).

**Comment by drummer1154** [comment]
OK, thx, will wait a bit as suggested.

**Comment by chrisrimple** [comment]
I wonder if we can close this comment now and move all discussion to the Talk page on Wikipedia?

**Comment by gilgongo** [comment]
Yes, that's probably best. @corrados Do you agree?

**Comment by corrados** [comment]
Yes, good idea. So, I'll close this now.

**Comment by gilgongo** [comment]
As prophesied, the article has been nominated for deletion :-) 

https://en.wikipedia.org/wiki/Wikipedia:Articles_for_deletion/Comparison_of_Remote_Music_Performance_Software

I'll cast a vote...

**Comment by hselasky** [comment]
Maybe we can move the content here:
https://wiki.thingsandstuff.org/Jamming

**Comment by hselasky** [comment]
FYI
https://www.linuxquestions.org/questions/2020-linuxquestions-org-members-choice-awards-131/music-collaboration-platform-of-the-year-4175687384/

**Comment by gilgongo** [comment]
I think we have some decent grounds to contest the deletion and I've [stated that case](https://en.wikipedia.org/wiki/Wikipedia:Articles_for_deletion/Comparison_of_Remote_Music_Performance_Software) like a Wikilawyer. But let's see how the vote goes. I may be we can put the table into that other page https://en.wikipedia.org/wiki/Networked_music_performance

**Comment by drummer1154** [comment]
FYI: "This article was nominated for deletion on 24 December 2020. The result of the discussion was **keep**."
