### ISSUE TITLE
Default fader levels on entering new session

### ISSUE THREAD

**Issue by fleutot** [corrados/jamulus#782]
I'm not sure if this is a regression or if I just never noticed before.

Entering a new session has fader levels for connections that were there before at 100 %.
New connections (after me) honor "New Client Level".

Maybe there's a rationale behind that, but I personally use "New Client Level" to really mean "all others until I say otherwise". Because of that, I would expect the previously existing connections to get that level as well (but then the option maybe could have a better name, such as "Default Level of Other Clients").

**Comment by gilgongo** [comment]
Can't comment on first point, but:

> have a better name, such as "Default Level of Other Clients"

Yes. Trouble is whatever we put in the menu has to refer to the label of the field for that level value in the Settings I think? Unless we did it differently perhaps. 

BTW this reminds me we decided (somewhere...) not to use "Channel" but "User" in order that we can be clearer when referring to an actual audio channel as oppose to simply as person in your jam.

**Comment by corrados** [comment]
> Entering a new session has fader levels for connections that were there before at 100 %. New connections (after me) honor "New Client Level".

It depends how old the Jamulus server is. If it is a new Jamulus server version, then the "New Client Level" will also be applied to the users which were on the server before you entered the server.

But note that the New Client Level is not applied to clients which you had a sesson with before. For these users, the old level is stored.

If you do not want any stored levels/settings, then you can do the following: Start jamulus with the --inifile command line argument so that Jamulus starts with the default settings. Then you go to File menu and store the current fader settings (which are empty). Then you can start your normal Jamulus instance with all your settings and just before you enter the server, you can load the "current fader settings" file you just saved. But note that all your previous fader settings are then overwritten. So if you want to store them, you should store the current fader settings before you load the default file (which does not contain any stored levels).

**Comment by fleutot** [comment]
> It depends how old the Jamulus server is. If it is a new Jamulus server version, then the "New Client Level" will also be applied to the users which were on the server before you entered the server.

OK cool, that's probably what was happening!

**Comment by corrados** [comment]
Can we close this then?

**Comment by fleutot** [comment]
Yes
