### ISSUE TITLE
Changing the number of players to 20 from the default 10

### ISSUE THREAD

**Issue by corrados** [corrados/jamulus#884]
I just received a request to change the default number of supported clients at the Jamulus server from 10 to 20. I have no problems with changing this.

Opinions?

**Comment by dcorson-ticino-com** [comment]
I would not.  There is enough hardware out there that might have problems at 20.
It should be a deliberate decision knowing your hardware to go to more users.
Otherwise people would think it is a problem of Jamulus should it not work to satisfaction.

**Comment by corrados** [comment]
> There is enough hardware out there that might have problems at 20

I thought it would be more a problem of the internet speed rather than the CPU limitation. If you refer to the raspPi users, I think they are used to work with command line options and they will be more capable of adjusting the max. number of allowed users than the usual Windows users who just start the server GUI.

**Comment by dcorson-ticino-com** [comment]
> I thought it would be more a problem of the internet speed rather than the CPU limitation

For whatever reason.  
My comment is simply that I see people immediately dumping on Jamulus when the problem is quite somewhere else.
Instead of trying to find the problem and correcting it (such as lowering the input volume so there is no clipping) they claim Jamulus is useless.
I would prefer to avoid this by having default values that will not possibly lead to problems.
Is there a reason why the max users can't be set in the server GUI ?
Don

**Comment by nefarius2001** [comment]
Any reason they do not want to use the appropriate parameter to increase the max?
In my opinion defaults should be a start point, that definitively works and twerking parameters strays from

**Comment by corrados** [comment]
Ok, fine with me. So let's keep the default and do not change anything -> closed.
